- .babelrc.js
- .travis.yml
- package.json
- src/serverEntry.tsx
- tslint.json
- yarn.lock
> Hedvig-cli 1.2.0 

- .babelrc.js
- package.json
- src/App.test.tsx
- src/App.tsx
- src/clientEntry.tsx
- src/pages/Chat.test.tsx
- src/pages/Chat.tsx
- src/pages/Hedvig.tsx
- src/routes.ts
- src/serverEntry.tsx
- yarn.lock
~~kind of coupled with https://github.com/HedvigInsurance/web-survival-kit/pull/6 and https://github.com/HedvigInsurance/web-survival-kit/pull/7~~
Adds a basic page and a skeleton for some routing
> Routing + basic page

- src/server/page.tsx
> Fix global giraffe endpoint name

- package.json
- src/components/animations/LazyLottie.tsx
- src/components/hedvig/conversation/Conversation.tsx
- src/pages/Chat/state.tsx
- src/pages/Chat/steps/CurrentInsuranceInput.tsx
- src/pages/Chat/steps/Greet.tsx
- src/pages/Chat/steps/LivingSituationInput.tsx
- src/pages/Chat/steps/NameAgeInput.tsx
- src/utils/sessionStorage.ts
- src/utils/storage/MockStorage.ts
- src/utils/storage/ServerCookieStorage.ts
- yarn.lock
I think its very unnecessary to pull in a lib of this size if we only use like 1 or 2 functions from it, that are more kind of convenient helpers, rather than stuff that help us utilise the power of fp. so imo the easiest way to not waste time on these discussions is just kill kill kill 🔪🔪🔪
> Kill ramda ☠️💀🔪

- package.json
- src/server/page.tsx
- src/utils/apolloClient.ts
> Forward request (uu)id to giraffe

- src/server/middleware/enhancers.ts
As it turns out http errors are thrown in koa. If we catch all errors and return internal server error if we get _any_ error we're gonna make i.e. `401` -> `500` which isn't awesome, i.e. on 404 or or 401. Like... all requests on staging atm.
This fixes it.
ping @HedvigInsurance/clients
> Fix error handling of http response errors

- src/pages/Chat/components/LoadingScreen.tsx
> Add interim lodaing screen (until we have fancy animations n stuff)

- package.json
- yarn.lock
> Upgrade CLI and WSK

- src/pages/Sign/sections/SignSubscription.tsx
- src/pages/Sign/sections/SignUp.test.tsx
So we don't risk missing events
> Query sign state before starting subscription

- src/pages/Chat/steps/AddressInput.tsx
- src/pages/Chat/steps/NameInput.tsx
This allows forms to once again be auto-completed by browsers.
Also some fields will automatically gain focus! :tada:
> Improve form autofill ergonomics with metadata attributes

- src/pages/Chat/steps/CurrentInsuranceInput.tsx
> Fix so one can proceed with a current insurance company

- src/server/apolloClient.ts
- src/server/config.ts
- src/server/middleware/helmet.ts
- src/server/page.tsx
- src/serverEntry.tsx
> Always use proper giraffe endpoints

- src/server/middleware/helmet.ts
> Add a pile of 💩 to csp headers

- src/pages/Offer/sections/HedvigInfo.tsx
- src/pages/Offer/sections/HedvigSwitch.tsx
- src/pages/Offer/sections/InsuranceCoverage.tsx
- src/pages/Offer/sections/Offer.tsx
> Add some fixes for IE

- src/pages/Chat/containers/CreateOfferContainer.test.tsx
- src/pages/Chat/containers/CreateOfferContainer.tsx
- src/pages/Chat/utils/test-utils.ts
- src/utils/postalNumbers.ts
> Don't send postal numbers with spaces

- src/pages/Offer/index.tsx
- src/pages/Offer/sections/InsuranceCoverage.tsx
- src/pages/Offer/sections/InsuredAmount.tsx
- src/pages/Offer/sections/OtherInfo.tsx
- src/pages/Offer/sections/Terms.tsx
> One big section containing 4 smaller

- src/pages/Chat/ChatConversation.tsx
- src/pages/Chat/steps/Greet.tsx
- src/pages/Offer/sections/GetInsured.tsx
- src/pages/Offer/sections/Offer.tsx
- src/pages/Sign/sections/SignUp.tsx
the attribute `data-hj-supress` makes hotjar not pick this information up during recording.
See https://help.hotjar.com/hc/en-us/articles/115012439167-Suppressing-Content-in-Recordings#supressing-specific-elements-in-recordings for more information!
> Hide it from HotJar

- src/clientEntry.tsx
- src/utils/sessionStorage.test.ts
- src/utils/sessionStorage.ts
- src/utils/storage/MinimalStorage.ts
- src/utils/storage/MockStorage.ts
- src/utils/storage/ServerCookieStorage.ts
Yeh, the session shouldn't live forever if the user don't close their browser but leave the page.
> Session invalidation

- src/components/TopBar.tsx
- src/components/hedvig/conversation/Conversation.tsx
- yarn.lock
> Upgrade packages

- src/components/hedvig/conversation/Conversation.tsx
- src/pages/Chat/steps/CreateOffer.test.tsx
- src/pages/DontPanic/DontPanic.tsx
- src/utils/storage/ServerCookieStorage.ts
- yarn.lock
Just upgrade loadsa loadsa packages
> Package lovin ❤️

- app.json
- hedvig.config.js
- package.json
- src/pages/Referral/index.tsx
- src/pages/Referral/util.ts
- src/server/config.ts
- src/server/page.tsx
I made some bad assumptions about how the links work. Now they work fine.
> Fix: Referral firebase links

- src/clientEntry.tsx
- src/pages/Referral/index.tsx
- src/server/page.tsx
> Tablet support!

- src/components/hedvig/chat.tsx
- src/utils/globalStyles.tsx
and set correct weights for geomanist
> Remove merriweather

- src/pages/Chat/index.tsx
- src/pages/Offer/DiscountAutoConsumer.tsx
- src/pages/Offer/containers/RedeemCodeMutation.tsx
- src/pages/Offer/index.tsx
- src/pages/Offer/sections/offer/Discount.tsx
- src/utils/sessionStorage.ts
Turns out we already had infrastructure for this lmao
> Automatically consume discount codes provided through query parameters

- src/containers/OfferContainer.tsx
- src/pages/Offer/components/PriceAndInclusions.tsx
> Display campaign owner on free months campaigns

- src/pages/Offer/sections/offer/Discount.tsx
Design wanted it to stick out a little bit less  😄
> Tweak styling on discount button

- src/pages/Offer/components/Wrapper.tsx
- src/pages/Offer/sections/offer/DiscountBubble.tsx
- src/pages/Offer/sections/offer/index.tsx
- src/pages/Sign/sections/SignUp.tsx
- Discount badge is visible in responsive mode on both offer and sign card
- Tightened the offer card design by adding some spacing around the cards
<div style="width: 100%">
</div>
> Responsive fixes

- package.json
- src/pages/ChatV2/index.tsx
- src/routes.ts
- src/server/middleware/helmet.ts
- yarn.lock
Todos for later:
- Load data from GraphQL
- Types for data from angel
- Use some kind of browser history implementation
- Decide which file to load from angel
> Embark MVP

- src/pages/Sign/sections/SignSubscription.tsx
> Fix studentkortet issue

- package.json
- src/pages/Embark/createQuote.ts
- src/pages/Embark/houseInformation.ts
- src/pages/Embark/index.tsx
- src/pages/Embark/personalInformation.ts
- yarn.lock
Note that these do not work 100% currently - some fixes are required on the backend side. Let's review the implementation for now and make adjustments later on if necessary
> Concrete API Implementations

- src/pages/Embark/index.tsx
- src/routes.tsx
- src/utils/tracking.ts
Bonus: Adtraction no longer breaks the world
> Angel data from GraphQL

- package.json
Bonus: Do not use an outdated and insecure yarn
> Bump embark

- src/pages/OfferNew/Perils/mock.tsx
Edited all peril copy for Villa insurance
> Updated Peril copy for Villa

- src/pages/OfferNew/Perils/mockPerils/house.tsx
Row 108: What's the name of the Skadedjur icon?
Row 126: What's the name of the Ombyggnation/Drill icon?
> Add Skadedjur and Ombyggnation to Villa perils

- package.json
- src/pages/Embark/index.tsx
- yarn.lock
+ Bonus: use sessionStorage instead of localStorage for embark
> Embark tracking

- src/pages/OfferNew/Perils/mockPerils/brf.tsx
Row 263: Bostadsrättstillägg icon
> Updated Peril copy BRF

- src/pages/Embark/index.tsx
Apparently this lead to leads becoming users in Intercom for some reason, so removing it while figuring out what the heck 🤔
> Remove Intercom update call

- src/components/animations/LazyLottie.tsx
- src/new-components/DateInput/index.tsx
- src/pages/Chat/components/LoadingScreen.tsx
- src/pages/FourOhFour.tsx
- src/pages/OfferNew/Perils/perilData/index.ts
just makes it easier to know when things are loaded
> Name the code splits

- src/generated/graphql.tsx
- src/graphql/MemberOffer.graphql
- src/pages/OfferNew/Introduction/Sidebar/index.tsx
- src/pages/OfferNew/Introduction/Sidebar/utils.ts
These codes work in test:
Invite: `st0xv8`
Percent: `ppp`
Free months: `bank`
> Percent discount and clearer invites

- src/new-components/inputs/index.tsx
> Make drop-down arrow clickable in edit quote

- package.json
- src/generated/graphql.tsx
- src/graphql/MemberOffer.graphql
- src/new-components/inputs/index.tsx
- src/pages/OfferNew/Checkout/CheckoutContent.tsx
- src/pages/OfferNew/Checkout/index.tsx
- src/pages/OfferNew/Introduction/Sidebar/StartDate.tsx
- src/pages/OfferNew/Introduction/Sidebar/index.tsx
- src/pages/OfferNew/index.tsx
* Solved a bug where we were not actually fetching the start date on the quote, making the date picker always show "Today" even though you picked another date previously
* Added the start date to the checkout, reusing the same component used in the sidebar
> Show start date on checkout

- src/utils/tracking.ts
> Track house with Adtraction

- src/data/graphql.tsx
- src/graphql/ReferrerName.graphql
- src/pages/Forever/components/Intro/IntroStories.stories.tsx
- src/pages/Forever/components/Intro/IntroStories.tsx
- src/pages/Forever/components/Intro/components.tsx
- src/pages/Forever/components/Intro/index.tsx
- src/pages/Forever/useRedeemCode.ts
- src/utils/apolloClient.ts
- src/utils/tracking.ts
> Hedvig Forever: show correct name

- src/server/middleware/helmet.ts
Enabling the GTM-debugger view to function properly
> Add tagmanager css to csp

- src/routes.tsx
Will ofc not show anything until the embark flow is merged
> [HVG-88] Bypass dk intro screen and go to directly to embark for now

- src/server/page.ts
Remove printed comma in body due to map function
> Remove comma in body

- .github/PULL_REQUEST_TEMPLATE.md
Some new wording, a typo fixed.
Typos are bad and better wording is good 🙃
> Edit PULL_REQUEST_TEMPLATE slightly and fix typo

- src/client/data/graphql.tsx
- src/client/graphql/Contracts.graphql
Remove Contract query.
It's unused.
> Chore / Remove Contract query

- src/client/data/graphql.tsx
- src/client/pages/OfferDebugger/components/QuoteData.tsx
- src/client/pages/OfferDebugger/components/QuoteFormDenmark.tsx
- src/client/pages/OfferDebugger/components/QuoteFormNorway.tsx
- src/client/pages/OfferDebugger/components/QuoteFormSweden.tsx
- Fix creating SWEDISH HOUSE quote.
- Use uppercase quote types.
- Fix NO/DK/SE quote inputs to match JSON schema
- Handle UW limit errors in debugger.
Some updates have landed in Underwriter so it was time to make the same changes here.
> Feature / Update offer debugger to match JSON schema

- src/client/data/graphql.tsx
- src/client/graphql/Campaign.graphql
- src/client/pages/Forever/index.tsx
- src/client/utils/campaignCode.ts
- Create QuoteCartForeverPage which redirects the user to the new-member landing page and saves the campaign code in sessionStorage. The flow is thereby shortened and we bypass the intro animation. The idea is to enable the intro later when the API allows (Right now we don't get the name of the person who has given the forever code).  
- Create new Campaign query that validates the campaign code. 
- We currently use an endpoint that requires an auth token, the idea is to migrate to a new endpoint later on. 
To be able to use the Quote Cart API on the Forever Page! 
**Ticket(s): [GRW-589]**
[GRW-589]: https://hedvig.atlassian.net/browse/GRW-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Quote Cart Api Forever page

- src/client/data/graphql.tsx
- src/client/graphql/QuoteBundle.graphql
@mightyost found a bug:
This should fix the localization on extra buildings :slightly_smiling_face:
> Added locale to quoteBundle query

- package.json
- src/client/pages/Embark/index.tsx
- yarn.lock
Upgrade Embark & implement `QuoteCartOfferRedirect` hook.
Co-Authored-By: amandaflod <59652803+amandaflod@users.noreply.github.com>
To use new features from Embark: `ConstantVariable`, `QuoteCartOfferRedirect`, `InsurelyAction`, Markdown support in `Message`.
> GRW-592 / Feature / Upgrade Embark v2.4.0

- src/client/pages/Landing/landingPageData.ts
- src/routes.tsx
- Add separate route for quote cart needer flow Sweden. 
- If Quote Cart Api is enabled the user will be redirected to new Embark flow
**Ticket(s): [GRW-609]**
[GRW-609]: https://hedvig.atlassian.net/browse/GRW-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature / Quote Cart Needer Flow

- package.json
- yarn.lock
Update Embark
Bugfix in Embark for Footer component
>  upgrade embark version to 2.4.1

- src/client/data/graphql.tsx
- src/client/graphql/CreateQuoteBundle.graphql
- src/client/pages/Offer/Introduction/DetailsModal/index.tsx
- src/client/pages/OfferDebugger/components/QuoteData.tsx
- src/routes.tsx
Also update graphql client to match new schema changes.
Current setup overrides existing endpoints:
- /new-member/sign/success
- /new-member/sign/fail
> Hotfix / Reorder routes to not override existing endpoints

- src/client/l10n/locales.ts
- src/client/pages/ConnectPayment/index.tsx
- src/client/pages/Embark/LanguagePicker.test.tsx
- src/client/pages/Embark/LanguagePicker.tsx
- src/client/pages/Embark/__snapshots__/LanguagePicker.test.tsx.snap
- src/client/pages/Embark/index.tsx
- src/client/pages/Forever/components/RedeemCode.tsx
- src/client/pages/Landing/Landing.tsx
- src/client/pages/Offer/index.tsx
- src/client/pages/OfferNew/index.tsx
- src/client/utils/hooks/useFeature.ts
Implement feature flag for customer service phone  …
Add color prop to correctly style language picker.
Update snapshots.
Key solutions not available during x-mas.
> Temporarily disable phone number

- src/client/pages/Embark/index.tsx
- src/client/pages/OfferDebugger/Debugger.tsx
- src/client/utils/hooks/useCreateQuoteCart.ts
- src/shared/sessionStorage.ts
Add new clear session method on storage.
Add new hook to create quote cart.
We want to avoid situations where we mix up tokens for different sessions.
**Ticket(s): [GRW-698]**
[GRW-698]: https://hedvig.atlassian.net/browse/GRW-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-698 / Feature / Clear session/token when creating new quote cart

- src/client/pages/Embark/index.tsx
Don't automatically re-create a quote cart unless specifically triggered.
If the component is mounted a second time, we re-run use effect hook.
> Avoid automatic quote cart re-creation

- src/client/utils/campaignCode.ts
Update `CampaignCode` interface to match existing cookie-based implementation.
Makes sense to keep using the existing solution unless we have a reason to move away from it.
> Store campaign code in cookie

- src/server/config.ts
Set feature flags as disabled if no environment variable is found.
Production env didn't have some feature flags set and that caused a runtime error.
> Set features as disabled if no env var is found

- src/client/pages/OfferNew/Checkout/InsuranceSummaryTermsLinks.tsx
Updated the styling of the terms and conditions in the checkout.
**Ticket(s): [GRW-647]**
Mobile: 
Desktop:
[GRW-647]: https://hedvig.atlassian.net/browse/GRW-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature / Terms and conditions checkout styling

- src/client/utils/tracking/adtraction.ts
- src/routes.tsx
- `serverRouteData` with `titleTextKey` added to landing page route in order to fix the page title being "undefined" for a moment when page loads (before the page title rendered with react-helmet on the client pops up)
This weirdly enough also seems to fix the bug of the `/connect-payment` page described below 🤔 
- A check if we have both window (window as any).Sentry is added before trying to run `(window as any).Sentry.captureMessage(e)` in `adtraction.ts`
The `/connect-payment` page i broken. When signing in Denmark and Norway the redirect is just a white page (seems to not be an issue for Sweden though). This is caused by `ADT` being `undefined` (line 116 in `adtraction.ts`) and when moving into the `catch` on line 130 everything crashes since `(window as any).Sentry` is also …
> GRW-717 / Fix / Routing bugs

- src/client/pages/Embark/index.tsx
> Fix redirect to offer page

- src/client/components/Headline/Headline.stories.tsx
Headline.stories fixes: 
- Instead of just exporting one `default` "story" with light background, two stories are exported - one `LightBackground` and one `DarkBackground`
- Better typing
- @guilhermespopolin pointed out in my previous PR that this was a better way to do it :)
**Light background, `colorVariant` `'dark'`:**
**Dark background, `colorVariant` `'light'`:**
> Fix / Headline Story

- src/client/pages/Offer/index.tsx
Remove redirect on (quote cart) offer page.
I don't think this is strictly necessary since no one will end up on that page unless they go through a quote cart enabled Embark flow.
It also makes testing in staging easier since we don't need to turn on the quote cart API for that whole market.
> Remove redirect on offer page

- src/client/pages/OfferNew/Checkout/index.tsx
Remove phoneNumber from canInitiateSign
Checkout cannot be signed.
> Remove phoneNumber from canInitiateSign

- src/routes.tsx
New route for DK home Embark flow with Quote Cart
We need a new route so we can test Quote Cart in DK.
**Ticket(s): [GRW-726]**
[GRW-726]: https://hedvig.atlassian.net/browse/GRW-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-726 / Feature / Add route for DK home quote cart flow

- src/routes.tsx
New Embark route added.
So we can test quote cart in NO.
> Add new route for NO home flow with Quote Cart

- src/routes.tsx
Add new route.
So we can test the flow in staging.
> Add route for SE home switcher + quote cart

- src/client/pages/Offer/Checkout/index.tsx
See PR title.
The request to generate access token was called twice which resulted in an error.
This caused the UI to not redirect to the connect payment page.
> Add check to avoid completing checkout twice

- src/client/pages/Offer/Checkout/index.tsx
Use separate state to track if we started the complete checkout step.
Tested locally.
It was causing issues to rely on the "sign UI state" since it's used for tracking other things.
> Fix trigger to complete checkout

- src/client/pages/Offer/Checkout/index.tsx
See title.
The check if we already called the function was accidentally reset in the `finally` block which is incorrect.
Also moved the check inside the complete checkout function to co-locate that logic.
Tested locally.
**Ticket(s): [GRW-744]**
[GRW-744]: https://hedvig.atlassian.net/browse/GRW-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-744 / Fix / Avoid multiple calls to create access token

- src/client/pages/Offer/Checkout/index.tsx
- src/client/pages/Offer/PageWrapper.tsx
- src/client/pages/Offer/index.tsx
- src/client/utils/tracking/gtm.ts
- src/client/utils/tracking/tracking.ts
Add optional Quote Cart ID property to GTM tracking for all offer page events.
We need to track this with the new Quote Cart API since we no longer create the member ID until sign.
**Ticket(s): [GRW-747]**
[GRW-747]: https://hedvig.atlassian.net/browse/GRW-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-747  / Feature / Track quote cart ID as part of `offerData`

- src/client/pages/Offer/Checkout/index.tsx
As of the creation of the new EditBundledQuote Mutation as part of the QuoteCart API, we decided to use it for startDate update as well as the checkout form.
This PR reverts to using CreateQuoteBundle Mutation instead.
- There are outstanding issue with the EditBundleQuote Mutation that are taking time to solve and slowing the delivery of the project.
- The CreateQuoteBundle Mutation is works very well for the job and in some aspects is superior as it makes editing multi-quote Bundles atomic and makes handling editing errors better.
**Ticket(s): [GRW-740]**
https://user-images.githubusercontent.com/89857278/150977675-2800a2ba-cb4a-46d1-9b26-0594e11639ef.mov
[GRW-740]: https://hedvig.atlassian.net/browse/GRW-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> GRW-740 Revert to using CreateQuoteBundle for checkout form

- src/routes.tsx
Add new routes:
- Home + Accident
- Home + Accident + Travel
...so we can test it!
> Add routes for new DK home accident travel bundle flows with Quote Cart

- e2e/cypress.json
- e2e/cypress/integration/no-english-flows.spec.ts
- e2e/cypress/integration/no-norwegian-flows.spec.ts
- src/client/pages/Offer/Introduction/Sidebar/index.tsx
- src/client/pages/OfferNew/common/PriceBreakdown.tsx
Update e2e test for NO English flow.
Remove individual timeouts to rely on new default.
Add `data-testid` attribute to target offer page elements.
Easier to run these than manually clicking through Embark!
> Add new e2e test for NO Norwegian flows

- src/client/pages/Offer/Checkout/index.tsx
- src/client/pages/Offer/Introduction/Sidebar/CampaignCodeModal.tsx
- src/client/pages/OfferNew/Introduction/Sidebar/DiscountCodeModal.tsx
Fix the add voucher code button on the offer page. Reported in the quote cart testing session. 
I believe this breaks after the new input-fields PR and I think it is easier to roll forward than roll back. There was some code scouting to be done in the file but I did not want to block the release. 
Now if you type something the button becomes clickable. 
https://web-onboardi-bugfix-grw-kykdxa.herokuapp.com/se-en/new-member/debugger
>  bugfix/GRW-772/Add voucher Code

- src/client/components/inputs/index.tsx
The select boxes have blue text and gray background on iOS. It's now fixed.
**Ticket(s): [GRW-776]**
[GRW-776]: https://hedvig.atlassian.net/browse/GRW-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix select color + background (iOS)

- .github/workflows/deploy-storybook.yml
- .gitignore
A GH action workflow to deploy Storybook
So we can show it to designers/stakeholders.
> Add workflow to deploy storybook

- src/client/pages/Landing/landingPageData.ts
Use quote cart feature flag to enable new Embark flows in NO
So we can go live and roll back easily without having to change any code.
> Enable Quote Cart flows in NO 🎉

- src/routes.tsx
Disable the redirect for NO quote cart flows in production
Luckily I noticed this already in the shadow environment! :D
> Enable NO quote cart routes in prod

- src/routes.tsx
> Enable quote cart offer page in prod

- src/client/components/CampaignBadge/CampaignBadge.tsx
Fix spacing between campaign badges.
There was an issue when they stacked on top of each other.
I would like to use Flex gap but it doesn't have great support in browsers.
So I went with a margin hack I found online and references the source.
https://coryrylan.com/blog/css-gap-space-with-flexbox
> Fix campaign badge spacing

- package.json
- yarn.lock
Fixes two issues:
- `MultiActionVariable` now supports a "from" (store) attribute separate from the "key" attribute.
- Fixes issue with selected insurance types in quote cart redirect
To launch SE quote cart
**Ticket(s): [GRW-795]**
[GRW-795]: https://hedvig.atlassian.net/browse/GRW-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update embark v2.6.0

- src/client/pages/Offer/Introduction/Sidebar/CancellationOptions.tsx
https://user-images.githubusercontent.com/19200662/156150421-1cf9bce3-ea02-4af5-a92a-ef9c304fe832.mov
**Ticket(s): [GRW-860](https://hedvig.atlassian.net/browse/GRW-860)**
https://user-images.githubusercontent.com/19200662/156153159-31d90025-9bfd-478e-8513-923f5943fc7e.mov
> fix(CancellationOptions): disable checkbox while choosing date

- src/client/pages/Offer/Introduction/DetailsModal/index.tsx
Make sure to override the default value if it's part of the form.
> Fix editing `isStudent` (offer page)

- src/client/pages/Landing/landingPageData.ts
- src/routes.tsx
We already do this for NO but this enables the same functionality in SE/DK.
For testing quote cart.
> Display quote cart flows when enabled

- src/client/components/LoadingPage.tsx
- src/client/pages/Embark/index.tsx
- src/client/pages/Forever/index.tsx
- src/client/utils/globalStyles.tsx
Remove overrides.
Update loading page to light gray.
I think it's time. The default text color is already dark gray so makes sense that default background color it light 😅 
I tried verifying all pages.
This will also fix it so the scrollbar is dark and visible! ping @guilhermespopolin 
Scrollbars:
Loading page:
https://user-images.githubusercontent.com/1220232/157210931-ff647e50-6ff4-4735-9d70-e5deac0c6313.mov
> GRW-889 / Fix / Make default body background light gray

- src/client/pages/Debugger/ActualDebugger.tsx
- src/client/pages/Debugger/components/QuoteData.tsx
- src/client/pages/OfferDebugger/Debugger.tsx
- src/client/pages/OfferDebugger/components/QuoteData.tsx
> Update styles on debugger to match white theme

- src/client/apolloClient.ts
- src/server/page.ts
- src/shared/sessionStorage.ts
Send with every Apollo request.
Required for CPAS.
> Implement device ID

- src/client/pages/Offer/Introduction/Sidebar/index.tsx
- src/client/pages/OfferNew/Introduction/Sidebar/DiscountCodeModal.tsx
- src/client/pages/OfferNew/Introduction/Sidebar/index.tsx
- src/client/utils/campaignCode.ts
Replace manual cookie handling with `CampaignCode` interface.
Don't overwrite campaign code if already added to quote cart.
We want to send links directly to the offer page (magic link) with a campaign code when retargeting users that never signed.
> GRW-888 / Feature / Pickup saved campaign code on offer page

- src/client/pages/Offer/Introduction/HeroOfferDetails.tsx
If URL includes `showEdit=true`.
For experiment with the 3-second quote!
> Add option to show edit modal on launch

- src/client/data/graphql.tsx
- src/client/graphql/fragments/CampaignDataFragment.graphql
- src/client/pages/OfferNew/utils.ts
- src/client/utils/tracking/adtraction.ts
Update GraphQL types, remove references to NO accident youth.
> GRW-768 / Fix / Remove campaign.owner from fragment

- src/client/pages/Forever/index.tsx
> Switch to quote cart forever page

- src/client/pages/Forever/index.tsx
Since the backend returns error for all forever codes.
> Skip validation of campaign code

- src/client/data/graphql.tsx
- src/client/graphql/Campaign.graphql
> Remove campaign query

- src/client/pages/Offer/Introduction/DetailsModal/Details/SwedishHouseDetails.tsx
- src/client/pages/Offer/Introduction/DetailsModal/Details/components/DetailInput.tsx
- src/client/pages/Offer/Introduction/DetailsModal/Details/components/Details.styles.tsx
Update style of "add" button.
Refactor extra building input slightly.
In preparation for 3 second quote.
**Ticket(s): [GRW-923]**
[GRW-923]: https://hedvig.atlassian.net/browse/GRW-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move extra buildings to top of edit modal

- src/client/pages/Offer/Introduction/DetailsModal/Details/SwedishApartmentDetails.tsx
- src/client/pages/Offer/Introduction/DetailsModal/index.tsx
Show input for apartment quotes in SE.
Update `subType` based on `isStudent` input.
Refactor a bit.
We want this for 3 second quote.
Since we show this for all danish users I think it's fine to show for all swedish users
**Ticket(s): [GRW-921]**
[GRW-921]: https://hedvig.atlassian.net/browse/GRW-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow editing student for SE apartment

- src/client/pages/ConnectPayment/components/AdyenCheckout.tsx
Small change after talking to adyen support
Let's try to get apple pay out soon
> removed amount object in apple pay

- src/client/pages/ConnectPayment/components/AdyenCheckout.tsx
Hope this will fix apple pay integration
To fix apple pay
> removed applepay.configuration and reverted to amount object

- src/client/utils/storage/ServerCookieStorage.ts
Avoid decoding `undefined` as "undefined" (string).
The previous implementation caused the value `undefined` to be decoded and returned as the string "undefined".
> GRW-977 / Fix / Fix how cookies are decoded

- src/client/pages/Checkout/CheckoutDetails/CheckoutDetails.tsx
- src/client/pages/Checkout/CheckoutPayment/index.tsx
- src/client/utils/hooks/useQuoteCartData.ts
See title
Was hard to test pages if it keeps failing.
> bug on Refresh for Checkout pages

- src/client/api/quoteCartQuerySelectors.ts
- src/client/pages/Offer/Introduction/Sidebar/StartDate.tsx
Include all individual quotes in mutation (not just selected).
We have a bug in SE when you select a single quote bundle and edit start date.
Then we run a mutation to add only that insurance to the quote cart which removes any other quotes (accident). This means that there's only one possible variation left so the up-sell options disappear.
**Ticket(s): [GRW-996]**
[GRW-996]: https://hedvig.atlassian.net/browse/GRW-996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-996 / Fix / Fix bug in start date mutation

- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
- src/client/pages/Checkout/CheckoutPayment/ContactInformation/ContactInformation.tsx
- src/client/pages/Checkout/shared/Footer.tsx
- src/client/pages/Offer/Checkout/inputFields.tsx
Added the validateOnMount prop on formik to make sure the form is always validated, and disabled the footer button when there are form errors
To prevent users from submitting the form without any empty or incorrect fields
Now, after arriving without a ssn:
> GRW-986 / Disabled form submissions with incomplete fields and added initial validation

- .github/workflows/ci.yml
See title.
We are making a push to move off CodeFresh so this aims to replace it and use GitHub Actions for our CI pipeline.
See: https://hedviginsurance.slack.com/archives/C9K7XRQ0G/p1650626436696869
> Add CI workflow using GitHub Actions

- src/client/pages/Checkout/CheckoutDetails/CheckoutDetails.tsx
- src/client/pages/Checkout/CheckoutPayment/ContactInformation/ContactInformation.tsx
- src/client/utils/tracking/gtm.ts
Add tracking for page views for the new Checkout pages.
**Ticket(s): [GRW-758]**
[GRW-758]: https://hedvig.atlassian.net/browse/GRW-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-758 / Feature / Checkout tracking page views

- src/client/pages/OfferNew/Perils/DocumentCollection/index.tsx
> GRW-1012 / Fix / Pass a unique value to `key`-prop

- src/client/pages/Checkout/CheckoutDetails/components/DocumentLinks.tsx
See title.
Don't want to redirect user in the middle of checkout flow.
> GRW-1011 / Fix / Open document links in new tab

- package.json
- yarn.lock
This just bumps `embark` so we can get the fixes added by [embark-894](https://github.com/HedvigInsurance/embark/pull/894)
[GRW-1009](https://hedvig.atlassian.net/browse/GRW-1009)
[embark-894](https://github.com/HedvigInsurance/embark/pull/894)
> fix(GRW-1009): update embark@2.9.1

- src/client/pages/Download/components/DownloadHeadline.tsx
- src/client/pages/Download/components/DownloadPageContent.tsx
- src/client/pages/Download/components/GetAppButtons.tsx
- src/client/pages/Download/index.tsx
See title.
It's the last holdout!
> GRW-1013 / Feature / Update Download page to bright theme

- src/client/pages/OfferNew/index.tsx
Update language switcher to link to offer page.
Now it links to landing page so the user looses the offer.
> GRW-1018 / Fix language switcher on old offer page

- src/client/pages/OfferDebugger/components/CarFormSweden.tsx
- src/client/pages/OfferDebugger/components/QuoteData.tsx
- src/client/pages/OfferDebugger/components/QuoteFormSweden.tsx
Adds the possibility to create a quote for `SWEDISH_CAR`
It will be time-consuming to always have to go through the Embark flow to get a quote to be able to work with the updated offer page.
**Ticket(s): [GRW-1014]**
[GRW-1014]: https://hedvig.atlassian.net/browse/GRW-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1014 / Feature / Add SWEDISH_CAR as possible QuoteType

- src/client/pages/Offer/Checkout/InsuranceSummary.tsx
Handle uncaught error, show generic error message, and send error to sentry.
We noticed this error occurs if backend sends back a birth date from the 1800s.
Therefore I think it's best we still throw the exception but catch it and log it.
> GRW-983 / Fix / Handle error in insurance summary details

- src/client/utils/tracking/trackOfferEvent.ts
The tracking event was added twice due to an incorrect conditional.
This PR fixes that.
> Fix / Avoid calling tracking event twice

- src/routes.tsx
This enables the checkout/details and checkout/payment routes in production
CPAS rollout :D
> Fix / Enable CPAS routes in production

- src/client/pages/Offer/Checkout/InsuranceSummaryDetails.tsx
- src/client/pages/Offer/utils.ts
- src/client/pages/OfferNew/types.ts
Add car information to checkout panel, if exist.
Replace deprecated `useCurrentLocale`.
**Ticket(s): [GRW-1031]**
English:`1,000 mil/year` (I have a discussion ongoing about how to treat this translation):
Swedish: `1 000 mil/år`:
[GRW-1031]: https://hedvig.atlassian.net/browse/GRW-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1031 / Feature / Adapt checkout panel to car

- src/client/l10n/useLocalizeNumber.test.ts
- src/client/l10n/useLocalizeNumber.ts
- src/client/pages/Offer/Checkout/InsuranceSummaryDetails.tsx
- src/client/pages/Offer/utils.ts
- src/client/pages/OfferNew/InsuranceSelector/index.tsx
- src/client/pages/OfferNew/common/PriceBreakdown.tsx
- src/client/pages/OfferNew/common/price.tsx
Just a minor change to adjust formatting of (larger) numbers now that we have prices that might exceed 1,000.
Different languages have different thousand separators. For `sv` the number `1000` is rendered as `"1 000"` but for `en` it's `"1,000"`. This becomes important for pricing as we might render prices above 1,000 for car insurance.
**Ticket(s): [GRW-1031](https://hedvig.atlassian.net/browse/GRW-1031)** (not really specified in the ticket, just a UX consideration from my part)
Swedish:
English:
> GRW-1031 / Feature / Format numbers

- src/server/middleware/helmet.ts
Allow scripts from Google Pay domain.
Needed for adyen google pay option. Currently, we block that script.
> Fix / Add google pay domain to CSP

- src/client/pages/ConnectPayment/components/TrustlyModal.tsx
- src/client/pages/Offer/Checkout/UserDetailsForm.tsx
Fixed errors so we wound not see them in all PR's
Annoying
>  fixed errors for github actions

- src/client/components/Headline/Headline.tsx
- src/client/components/ModalNew.stories.tsx
- src/client/components/ModalNew.tsx
- Adds `ModalContent` content with basic padding styling
- Adds `textAlign` prop to `Headline`
- Adds story for NewModal
For Car we need to be able to show a Table inside a modal, and a centered headline:
Instead of creating yet another container for content inside a modal (we have several), I propose to have a standard one. The padding values are taken from Figma sketches.
**Ticket(s): [GRW-1062]**
https://user-images.githubusercontent.com/1343979/167138764-c63e3f2a-0895-4755-99fc-6ba8e4dcb0c2.mov
https://user-images.githubusercontent.com/1343979/167139094-391ab201-0c03-4d83-904a-f482ae923e29.mov
[GRW-1062]: https://hedvig.atlassian.net/browse/GRW-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1062 / feat / Fixes for Headline and Modal

- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
Added tracking to payment confirmed.
New changes to the flow of payment requires changing the tracking implementation
>  added payment confirmed tracking

- src/client/pages/ConnectPayment/components/AdyenCheckout.tsx
- src/client/pages/ConnectPayment/components/useAdyenCheckout.tsx
Log to datadog if unexpected error occurs.
The app crashes in production with error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
https://datadoghq.eu/rum/error-tracking?issueId=c6b5d57c-cf96-11ec-8ff0-da7ad0900005&start=1652189692835&end=1652193292835&paused=false
> Fix / Prevent clean-up function from crashing app

- src/client/pages/ConnectPayment/components/useAdyenCheckout.tsx
- src/client/utils/tracking/gtm/types.ts
Changed the way error tracking works for failed payment.
https://hedvig.atlassian.net/browse/GRW-1081
Changed flow so tracking needs to be updated.
>  change on error tracking cpas

- src/client/data/graphql.tsx
- src/client/graphql/fragments/QuoteDataFragment.graphql
- src/client/pages/Offer/Introduction/HeroOfferDetails.tsx
- src/client/pages/Offer/utils.test.ts
- src/client/pages/Offer/utils.ts
- src/client/pages/OfferNew/utils.ts
- src/client/utils/tracking/adtraction/adtraction.ts
This PR adds Car info to Offer page's Hero, if available in list of quotes.
The data that we get from VTR is a bit sketchy - sometimes either `makeAndModel` or `model` are empty, and sometimes they contain duplicate information.
Some examples from Fredrik L:
```
makeAndModel: TOYOTA T27
model: TOYOTA AVENSIS
```
```
makeAndModel: PEUGEOT L
model: 308
```
```
makeAndModel: VOLVO
model: XC60 T8 TWIN ENGINE
```
```
makeAndModel: HYUNDAI I20 1.4 A4COMFOR
model: I20
```
```
makeAndModel: VOLVO M + V50
model: null
```
That's why the `getCarMakeAndOrModel` method does some splitting, filtering and joining.
This is added so that users know which car they've been given a quote for.
**Ticket(s): [GRW-1002]**
[GRW-1002]: https://hedvig.atlassian.net/browse/GRW-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> GRW-1002 / feat / Add car info to Offer page's hero

- src/client/pages/Embark/addressAutocompleteProvider.ts
See title.
Currently we don't return anything which causes Embark to show nothing and the user get's stuck in the flow.
Now they are able to select to put in their address manually.
> Fix / Return empty array when API fails

- src/client/utils/tracking/gtm/trackOfferEvent.ts
> typo in tracking file 

- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
we had a conflict and this got merged with the wrong colors. reverted.
> revert button colors conflict

- src/client/data/graphql.tsx
- src/client/graphql/QuoteCart.graphql
- src/client/pages/OfferNew/InsuranceSelector/Card.tsx
- src/client/pages/OfferNew/InsuranceSelector/Selector.stories.tsx
- src/client/pages/OfferNew/InsuranceSelector/Selector.tsx
- src/client/pages/OfferNew/InsuranceSelector/index.tsx
If we get `description` from BE we add it to the Selectable Insurance Cards.
Result:
Design:
**Ticket(s): [GRW-1093]**
[GRW-1093]: https://hedvig.atlassian.net/browse/GRW-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add description to Selectable Insurance Cards when one is provided

- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
Added 5rem padding-top to CheckoutPayment to prevent overlap with the logo
CPAS rollout
**Ticket(s): [GRW-1097]**
[GRW-1097]: https://hedvig.atlassian.net/browse/GRW-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix/GRW-1097/CheckoutPayment padding-top

- src/client/components/CallCenterPhoneNumber/CallCenterPhoneNumber.tsx
- src/client/pages/Offer/Checkout/index.tsx
- src/client/pages/OfferNew/InsuranceSelector/index.tsx
GRW-1126: Compare button text should change size as body text above does, when on small screen
GRW-1127: Align labels for start date in checkout panel
GRW-1123: Phone opening hours text should be grey100
> Fix / Offer page small fixes car

- src/server/middleware/quoteCart.ts
> Fix / Show site in case of API error

- package.json
- yarn.lock
Update to latest Embark that can compare to null in Redirect components
This makes it possible to redirect user to an error screen when their car cannot be found
**Ticket(s): [GRW-1132]**
https://user-images.githubusercontent.com/1343979/170249596-e25fc082-c4fa-4abe-bed6-07f244ceaa4b.mov
[GRW-1132]: https://hedvig.atlassian.net/browse/GRW-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1132 / feat / Update to latest Embark that can compare to null in Redirect components

- src/client/pages/OfferNew/Perils/PerilModal.tsx
Recently fixed in market-web https://github.com/HedvigInsurance/market-web/pull/673
> Fix blue border on buttons in iOS

- src/client/pages/Checkout/CheckoutDetails/CheckoutDetails.tsx
- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
- src/client/pages/ConnectPayment/components/useAdyenCheckout.tsx
- src/client/pages/Offer/Checkout/index.tsx
- src/client/pages/Offer/index.tsx
- src/client/utils/tracking/hooks/useSendDatadogAction.ts
Log critical actions to Datadog with some important context.
Next up would be to add logging for errors.
It's very hard to follow what's happening in the app currently.
With these changes we will be able to get more context in the logs:
> GRW-1164 / Feature / Add Datadog actions to log checkout

- src/client/pages/Offer/Checkout/InsuranceSummaryDetails.tsx
Avoid nullish checks since 0 evaluates to false.
Some values are missing for House.
> Fix / Getting insurance summary values

- src/client/data/graphql.tsx
- src/client/graphql/PaymentStatus.graphql
- src/client/pages/ConnectPayment/components/AdyenCheckout.tsx
- src/client/pages/ConnectPayment/sections/ConnectPayment.tsx
- src/client/pages/ConnectPayment/useIsPaymentConnected.ts
* Redirect users to Download page if they have an active payment method
Per Robin's suggestion the first step is to just redirect the user straight to the Download page. Second step will be to introduce a new page that is tailored specifically to someone signing another contract.
* There's no need to connect payment if user already have an active payment method
**Ticket(s): [GRW-1152](https://hedvig.atlassian.net/browse/GRW-1152)**
> Redirect user to download page if payment is already connected

- src/client/api/quoteSelector.ts
Fix tracking for house DK ownership type
**Ticket(s): [GRW-1197]**
[GRW-1197]: https://hedvig.atlassian.net/browse/GRW-1197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1197 Fix tracking for house DK ownership type

- src/client/pages/Offer/Introduction/Sidebar/index.tsx
> Fix / Start date margin in Sidebar

- src/server/middleware/helmet.ts
Allow domains like:
- region1.google-analytics.com
- region2.google-analytics.com
- www.google-analytics.com
> Fix / Make sure we don't block analytics events

- src/client/pages/Offer/Introduction/Sidebar/StartDate.tsx
Fixes StartDate component for car in order to be able to change the date for all 3 contract types at the same time.
SE Car
**Ticket(s): [GRW-1215]**
[GRW-1215]: https://hedvig.atlassian.net/browse/GRW-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix/GRW-1215/Car StartDate reducer

- package.json
- src/client/pages/Embark/index.tsx
- yarn.lock
Update to latest Embark and add `EmbarkProvider::externalRedirects::Web(path: string)` so that we can redirect to any web route
We need to redirect users to a MW page when we cannot create a quote, see Jira ticket below.
**Ticket(s): [GRW-1212](https://hedvig.atlassian.net/browse/GRW-1212)**
> GRW-1212 / feat / Add EmbarkProvider::externalRedirects::Web 

- src/client/pages/Embark/index.tsx
Redirect with `location.href` instead of `history.push` in Embark's market web redirect.
`history.push` doesn't make a new HTTP request and for that reason the user won't get redirected to market-web but instead get a 404 in web-onboarding.
> Redirect with location.href instead of history.push

- src/server/middleware/helmet.ts
Simon says
https://hedviginsurance.slack.com/archives/C03CZNUA5K6/p1656942782630249
> Chore / Add new subdomain to CSP config

- src/client/pages/ConnectPayment/ConnectPaymentsDirectEntry.tsx
- src/client/pages/ConnectPayment/sections/ConnectPayment.tsx
Add intent query parameter to avoid redirect.
Skip rendering welcome message to users editing payment.
We are redirecting users with an active payment method.
It's possible to generate a payment link from HOPE to edit payment for existing users - we need this to make that work.
**Ticket(s): [GRW-1293]**
[GRW-1293]: https://hedvig.atlassian.net/browse/GRW-1293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix / No redirect when user is editing credit card

- .babelrc.js
- package.json
- yarn.lock
Fix many pages of storybook build warnings by updating babel and storybook
Removing warnings improve developer experience, we don't want warnings that we ignore
**Ticket(s): [GRW-1311]**
[GRW-1311]: https://hedvig.atlassian.net/browse/GRW-1311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Grw 1311/fix/update storybook fix build warnings

- src/client/api/quoteCartQuerySelectors.ts
- src/client/pages/Offer/ProductSelector/Selector.tsx
- src/client/pages/Offer/ProductSelector/index.tsx
- src/client/pages/Offer/index.tsx
- src/client/pages/Offer/types.ts
- integrate `ProductSelector` into _offer_ page
To enable _Pentagon House Cross Selling_
**Ticket(s): [GRW-1337](https://hedvig.atlassian.net/browse/GRW-1337)**
> feat(Offer): integrate ProductSelector

- src/client/pages/Download/components/DownloadPageContent.tsx
- src/client/pages/Download/useCrossSells.ts
Add hard-coded URLs to which page we want users to go to when they click the cross sell cards.
We need to know where to forward users. Unfortunately we have no BE support for managing where the links point to, so they're just hard-coded in FE code 😞 
**Ticket(s): [GRW-1386](https://hedvig.atlassian.net/browse/GRW-1386)**
> GRW-1386 / feat / Add links to cross sell cards, hardcoded with campaign code

- src/client/data/graphql.tsx
- src/client/graphql/PotentialCrossSells.graphql
- src/client/pages/Download/useCrossSells.ts
Pass `locale` to `potentialCrossSells` query.
Sometimes users get `Did not manage to compute locale` error message.
**Ticket(s): [GRW-1379](https://hedvig.atlassian.net/browse/GRW-1379)**
> Pass locale to cross-sells query

- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
Small refactor
**Ticket(s): [GRW-1414](https://hedvig.atlassian.net/browse/GRW-1414)**
> refact(CheckoutPayment): get search from useLocation hook

- src/client/components/buttons.tsx
- src/client/pages/Checkout/CheckoutDetails/CheckoutDetails.tsx
- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
- src/client/pages/Offer/Introduction/Sidebar/index.tsx
Fix a bug where selected insurances weren't being taken into account on _Checkout_ flows.
**Ticket(s): [GRW-1414](https://hedvig.atlassian.net/browse/GRW-1414)**
> fix(Checkout): make usage of selected insurances

- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.helpers.ts
- src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
- src/client/pages/Checkout/CheckoutPayment/index.tsx
Refetch quote cart before trying to sign in NO
Remove quote ids prop from CheckoutPayment component.
We sometimes try to sign quotes that are not related to the quote cart.
This happens when we edit quotes during checkout.
Therefore it's better to be safe and refetch the quote cart before trying to sign.
Haven't been able to test since I can't find a working NO SSN...
**Ticket(s): [GRW-1442]**
[GRW-1442]: https://hedvig.atlassian.net/browse/GRW-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Refetch quote cart before trying to sign in NO

- src/client/components/StandaloneProductCard.tsx
- src/client/pages/Offer/ProductSelector/Selector.tsx
This reverts #1132 
It wasn't approved by design
> Revert "refact(Selector): derivate state from URL"

- src/client/data/graphql.tsx
- src/client/graphql/PotentialCrossSells.graphql
- src/client/pages/Download/useCrossSells.ts
* Use web-specific content for cross-sells from PCMS
Because we want different content in the cross-sell promos on the web compared to what is shown in the apps.
**Ticket(s): [GRW-1452](https://hedvig.atlassian.net/browse/GRW-1452)**
> Use new web-specific content on PotentialCrossSells

- src/client/pages/Offer/ProductSelector/Selector.tsx
So, this simplifies the implementation of `Selector` without making any UI changes
This seems to be better implementation. Kind of the same idea was applied before with #1132 but that one was reverted because of some UI changes it came along with it.
**Ticket(s): [GRW-1445](https://hedvig.atlassian.net/browse/GRW-1445)**
> GRW-1445 - refact(Selector): remove internal state

- src/client/components/AdditionalProductCard.tsx
- src/client/components/StandaloneProductCard.tsx
Style updates for mobile
To look closer with designs
**Ticket(s): [GRW-1482](https://hedvig.atlassian.net/browse/GRW-1482)**
> styles(AdditionalProductCard): improved on mobile

- src/client/pages/Offer/AppPromotionSection.tsx
- src/client/pages/Offer/Introduction/Sidebar/SwitchingNotice.tsx
Animate to the switching promo section instead of using URL fragments
This way the user gets a better understanding of where on the page they are. 
Feedback from Zak
**Ticket(s): [GRW-1389]**
[GRW-1389]: https://hedvig.atlassian.net/browse/GRW-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1389 / feat / Animate to the switching promo section

- src/client/pages/Offer/Introduction/Sidebar/Sidebar.tsx
- src/client/pages/Offer/Introduction/Sidebar/useHasScrolledPastElement.ts
- src/client/utils/throttle.ts
Introduce a `useHasScrolledPastElement` hook and use that to set positioning for Sidebar.
This commit sets the Sidebar to absolutely positioned by default instead of fixed, and then sets fixed to the bottom of the screen when scrolled past. For desktop, to emulate the old fixed positioning we set fixed to top when scrolled past instead.
There's a concern that we might have a too long Sidebar now with the Car switching content, and that users might not be able to reach the "Continue to checkout" button if they have a small screen.
**Ticket(s): [GRW-1491]**
https://user-images.githubusercontent.com/1343979/190357647-253fbbe4-74b7-4a26-a9ad-5b4f4e35af92.mov
https://user-images.githubusercontent.com/1343979/190357804-f1bdef3b-9691-4d1a-847d-c9df4585fad4.mov
[GRW-1491]: …
> GRW-1491 / feat / Fix positioning for Sidebar for small screens

- src/client/pages/Offer/Checkout/index.tsx
Update `Checkout` component so it makes usage of `quoteCart_editQuote` mutation
It consists on a better method for updating quotes rather than recreating them
**Ticket(s): [GRW-1480](https://hedvig.atlassian.net/browse/GRW-1480)**
> GRW-1480 - refact(Checkout): make usage of quoteCart_editQuote mutation

- src/server/middleware/helmet.ts
* Add Insurely to Helmet's CSP
* Otherwise we cannot load the scripts and iframe from their domain
**Ticket(s): [GRW-1488]**
[GRW-1488]: https://hedvig.atlassian.net/browse/GRW-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1488 / chore / Add Insurely to Helmet's CSP

- src/client/pages/Download/components/CrossSells.tsx
* Track clicks on Cross sell promos on Download page
* Otherwise we won't know if they're useful or not
**Ticket(s): [GRW-1495]**
[GRW-1495]: https://hedvig.atlassian.net/browse/GRW-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1495 / feat / Add tracking for when users click Cross sell promo on Download screen

- package.json
- yarn.lock
* Update Embark to [2.16.0](https://github.com/HedvigInsurance/embark/blob/master/CHANGELOG.md)
* This adds more features for Insurely that we need for GRW-1517 
**Ticket(s): [GRW-1517]**
[GRW-1517]: https://hedvig.atlassian.net/browse/GRW-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Embark to 2.16.0

- package.json
- yarn.lock
- upgrade embark to [2.17.0](https://github.com/HedvigInsurance/embark/blob/master/CHANGELOG.md)
**Ticket(s): [GRW-1534]**
[GRW-1534]: https://hedvig.atlassian.net/browse/GRW-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> upgrade Embark to 2.17.0

- package.json
- yarn.lock
This installs Embark [2.18.1](https://github.com/HedvigInsurance/embark/pull/1037) that is needed for https://github.com/HedvigInsurance/embark/pull/1038 to work.
**Ticket(s): [GRW-1515]**
[GRW-1515]: https://hedvig.atlassian.net/browse/GRW-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Install Embark 2.18.1

- src/client/pages/Offer/useGetPromotions.ts
Only show Car Switcher promo (pictured) if the member is actually a switcher.
**Ticket(s): [GRW-1053]**
[GRW-1053]: https://hedvig.atlassian.net/browse/GRW-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GRW-1053 / feat / Only show Car Switcher promo if member is a car switcher

- src/client/components/DetailsModal/Details/components/DetailInput.tsx
- src/client/components/DetailsModal/index.tsx
Remove handling of `STUDENT_RENT` and `STUDENT_BRF`.
Backend has replaced this with `isStudent`.
Currently the edit modal is broken...
There's more places we use these values but let's merge this first and clean up more later!
**Ticket(s): [GRW-1635]**
[GRW-1635]: https://hedvig.atlassian.net/browse/GRW-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove STUDENT_RENT/BRF handling

- package.json
- yarn.lock
> Update Embark with iframe language fix

- package.json
- yarn.lock
See Embark PR for updates:
https://github.com/HedvigInsurance/embark/pull/1076
> Bump embark v2.23.1

- src/client/pages/Embark/index.tsx
- src/client/utils/tracking/gtm/trackExperimentImpression.ts
- src/client/utils/tracking/hooks/useTrackAbPurchaseFlowRedirect.ts
- src/server/abTestPurchaseFlowRedirect.ts
- src/shared/abPurchaseFlowRedirects.ts
Send experiment_impression event when first showing embark flow that matches experiment cookie
Allows us to track performance of A/B testing purchase flows in Google Optimize
> GRW-1721 / Feature / Track AB experiments

- src/client/pages/Download/useActiveContractBundles.ts
See title.
Request from Simon :)
**Ticket(s): [GRW-1826]**
[GRW-1826]: https://hedvig.atlassian.net/browse/GRW-1826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update campaign codes in cross sell links

- .env.example
- src/server/exchangeToken.ts
- src/server/serverEntry.tsx
Added /new-member/exchange-token ednpoint that gets accessToken, saves it cookie, then redirects to local URL specified by `next` param
Safe way to do cross-domain token transfer that does not rely on shared cookie and therefore works in any environment
> GRW-1798 / Feature / Exchange authorizationCode to accessToken when connecting payments for hedvig-com

- src/server/abTestPurchaseFlowRedirect.ts
- src/shared/abPurchaseFlowRedirects.ts
- Ignore experiment cookie when new variant weight is zero, allows to disable the test for returning members by changing env variable
- Next experiment ID for Car flow
Allows clean rollback of experiment without redeploy
> Feature / AB test improvements

- package.json
- yarn.lock
See title.
Update `InsurelyAction`.
-
**Ticket(s): [GRW-1756]**
[GRW-1756]: https://hedvig.atlassian.net/browse/GRW-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Embark to v3.1.0

- src/server/abTestPurchaseFlowRedirect.ts
- src/server/page.ts
Propery handle AB variant cookie lifetime.  Was using incorrect abstraction for it
Clients should see consisten variant of AB test
> Fix / Make AB variant cookie have 1w TTL as intended

- src/client/utils/tracking/gtm/trackExperimentImpression.ts
- src/client/utils/tracking/gtm/types.ts
- src/client/utils/tracking/hooks/useTrackAbPurchaseFlowRedirect.ts
- src/server/abTestPurchaseFlowRedirect.ts
Fix experiment_impression reports for Embark AB tests
Previous MR made experiment cookie HTTP-only and we lost client-side reporting
> Fix / Report experiment_impression

- src/client/pages/Payment/Payment.tsx
- src/client/pages/Payment/TrustlyIframe.tsx
Center trustly iframe on payment page.
Slightly tweak the height styles of the iframe.
> Center Trustly iframe

- src/client/pages/Payment/Breadcrumbs.tsx
- src/client/pages/Payment/Payment.tsx
Update Payment page designs
- spacing 
- colors
designers said so
> Update Payment page designs

- src/client/utils/tracking/gtm/dataLayer.ts
- src/client/utils/tracking/hooks/useTrackPageViewEvent.ts
Add siteVersion to user properties
Easier to filter data
> Add siteVersion to user properties

- src/client/apolloClient.ts
- src/client/containers/SessionContainer.test.tsx
- src/client/containers/SessionContainer.tsx
- src/client/utils/AppTokenRetrieval.tsx
- src/client/utils/authorization.ts
Add "Bearer " to Authorization header to make it standard-compliant
Make sure we apply it in all places where we set authorization header.  Current implementation feels like a mess, but I don't think changing it to one from raccoon/store now is a good idea
Stop relying on API Gateway fixing headers for us
> Add Bearer to authorization header in GraphQL client

- src/server/middleware/helmet.ts
Fix CSP to allow new PCMS peril icons (they come from amazon S3)
> Allow amazonaws.com as img-src since this is where new icons come from

- src/server/page.ts
- src/server/serverEntry.tsx
Directly call Giraffe from browser rather than using a proxy
Easier to setup with unified domain
No need to setup a proxy since we handle the CORS headers
> Directly call Giraffe endpoint rather than using a proxy

- src/client/l10n/callCenters.ts
Update call center info
We will no longer use Key solutions for phone sales
> Update call center info
