HedvigInsurance/web-onboarding

package.json
src/server/logging.ts
src/server/middleware/enhancers.ts
src/serverEntry.tsx
yarn.lock

Makes it possible to trace errors between requests without logging i.e. IPs, adds some timestamps, and avoids console.log which is awesome.
Example; This is what we'd get if we throw the following error in `App.tsx` `throw new Error('expected')`, simulating a render error in react
```
2018-10-03 11:24:45,672 INFO [app] Booting server on 8080 👢
2018-10-03 11:24:45,676 INFO [app] Not using any auth, server is open to the public
2018-10-03 11:24:45,681 INFO [app] Server started 🚀 listening on port 8080
Error: expected
at /Users/johanpalmfjord/dev/projects/web-onboarding/build/webpack:/src/App.tsx:17:76
at App (/Users/johanpalmfjord/dev/projects/web-onboarding/build/webpack:/src/App.tsx:17:62)
at processChild (/Users/johanpalmfjord/dev/projects/web-onboarding/node_modules/react-dom/cjs/react-d …
```

Improve logging

---

package.json
src/server/middleware/enhancers.ts
src/server/page.tsx

Oneliner fixes

---

app.json

woops. Forgot to add this. The apps crash if `GIRAFFE_ENDPOINT` isn't set

Make sure to copy giraffe endpoint from staging for pr instances

---

src/components/buttons.tsx
src/pages/Chat/components/LoadingScreen.tsx
src/pages/Chat/components/OfferCreationHandler.test.tsx
src/pages/Chat/components/OfferCreationHandler.tsx
src/pages/Chat/containers/ChatScreenContainer.test.tsx
src/pages/Chat/containers/ChatScreenContainer.tsx
src/pages/Chat/containers/CreateOfferContainer.tsx
src/pages/Chat/index.tsx
src/pages/Chat/steps/CreateOffer.test.tsx
src/pages/Chat/steps/CreateOffer.tsx

It's starting to get a little hairy with loads of cross-component dependencies, but imo it's still _acceptable_. However if we start getting more complexity then i think we should start looking into refactoring. Thoughts?
__edit__: realised we still need to run the query for the offer so the cache is warm when the user hits the offer page, but i think its quite minor. Lets implement that once #30 is done?
@HedvigInsurance/clients

Input -> offer transition

---

src/App.tsx

Setting `devtools=true` on the Constate `<Provider />` lets it interact
with `redux-devtools`, which makes for pleasant development.

Enable dev tools for Constate in non-prod envs

---

hedvig.config.js
src/components/TopBar.tsx
src/containers/SessionTokenGuard.test.tsx
src/containers/SessionTokenGuard.tsx
src/pages/Chat/ResetButton.tsx
src/pages/Chat/components/OfferCreationHandler.test.tsx
src/pages/Chat/components/OfferCreationHandler.tsx
src/pages/Download/sections/DownloadApp.tsx
src/pages/NewMemberLanding.tsx
src/pages/Offer/index.tsx
src/pages/Offer/sections/GetInsured.tsx
src/pages/Offer/sections/HedvigInfo.tsx
src/pages/Offer/sections/HedvigSwitch.tsx
src/pages/Offer/sections/InsuranceCoverage.tsx
src/pages/Offer/sections/Offer.tsx
src/pages/Offer/sections/PageDown.tsx
src/pages/Offer/sections/Terms.tsx
src/pages/Sign/sections/SignSubscription.tsx
src/pages/Sign/sections/SignUp.test.tsx
src/routes.ts
src/serverEntry.tsx

This simply prefixes the asset urls with `/new-member-assets` and all urls with `/new-member`
coupled with https://github.com/HedvigInsurance/web/tree/feature/web-onboarding

Let web reverse-proxy web-onboarding

---

app.json

it's used by Heroku, and this gives us more freedom

Kill some fields in app.json

---

src/components/TopBar.tsx

So we don't mash up environments when using staging

Remove hard-coded hedvig.com

---

src/server/middleware/helmet.ts

More CSP rules incoming! This should make branch.io's `sendSMS` work! 🤞

Fix sendSMS bug

---

src/server/middleware/helmet.ts

Apparently, branch.io requires another CSP rule for its `sendSMS` to function correctly...

Add CSP rule for bnc.lt

---

src/pages/Embark/index.tsx

Only browser history though, actual history is :ok_hand:

History sucks

---

src/pages/Referral/util.ts
src/utils/hooks/useTextKeys.ts

Will fix whitescreen-of-death in ie11 that has appeared

Don't use proxy for text keys if it doesn't exist in global scope

---

src/new-components/DateInput/index.tsx
src/pages/OfferNew/Introduction/Sidebar/DiscountCodeModal.tsx
src/pages/OfferNew/Introduction/Sidebar/StartDate.tsx

To solve the clipping problem with the date picker, I moved it into a modal within the sidebar.

Fix date input clipping issue

---

src/new-components/DateInput/index.tsx
src/pages/OfferNew/Introduction/Sidebar/StartDate.tsx

There's one outstanding issue in this PR: How will the backend respond if we send null on editQuote for startDate? Will it ignore it, or will it explicitly set the data to be null?
EDIT: I've updated this code to use `removeStartDate` 🙂

Allow choosing start date to be when previous insurance expires

---

src/pages/OfferNew/Compare/mock.ts

- Hedvig: 4.5 -> 4.6
- Trygg Hansa: 1.2 -> 2.2
- If Hem: 1.6 -> 4.3 
- Ica: 3.6 -> 3.3
- Länsförsäkringar: 1.6 -> 1.5
- Moderna: 1.9 -> 3.5

Update trustpilot scores

---

src/client/pages/OfferNew/Checkout/UserDetailsForm.tsx

Change input mode in ssn field to only display numbers in mobile.
`inputmode="numeric"` brings up the numeric keyboard on both Android and iOS. That covers most of our users but to be backwards compatible I added a pattern as well (I've got input from Sam and Oscar on this).
Because it's currently not a good solution for mobile users.

Set correct inputmode on ssn field

---

src/client/pages/OfferNew/Checkout/UserDetailsForm.tsx
src/client/pages/OfferNew/utils.ts

Change input type to `type=text` and set maxlength on input based on ssn length for the specific market
Input `type=number` is not optimal to use for ssn since it will increment on scroll or arrow clicks and can't have a max length. So in order to only input numbers we filter out all non-digit characters

Update ssn input type and ad maxlength

---

src/client/pages/OfferNew/Introduction/ExternalInsuranceProvider/Compare.tsx
src/client/pages/OfferNew/Introduction/HeroOfferDetails.tsx
src/client/pages/OfferNew/Introduction/index.tsx
src/client/pages/OfferNew/Perils/index.tsx

Add price comparison for switchers
Intermediate fix until we have de new design in place for price comparison. Not the most beautiful thing but it should do the trick over the weekend 😄
Commit for reference: https://github.com/HedvigInsurance/web-onboarding/pull/460/commits/ff4d1d852c7db7297446cadf74a1ffbc8f4ed151
Unlike the previous implementation, we don't need to shift content in mobile and desktop.
Will need someone to verify this that can compare insurances, setting up a review app. I mocked the data locally

Put back price comparison for switcher

---

src/client/pages/ConnectPayment/sections/ConnectPayment.tsx

Fix Image looking strange on Iphone simulator
**Please test staging with you iphone if this problem exists!**
Added height property
**Without height:**
**With:**

Fixed height by adding height: 100%  property

---

src/client/pages/LoginApp/LoginAppScreen.tsx

Make sure the simple sign login sends the correct token. 
Since we had wrapped the component in a `SessionContainer`, it creates a new session and overwrites the token we get from the apps.

Remove SessionContainer on login page

---

src/client/apolloClient.ts
src/client/utils/ExchangeTokenRetrieval.test.tsx

`Adding name to ApolloClient`
So that Giraffe knows which client caused the originating `Query/Mutation/Subscription`.

Add name to ApolloClient

---

src/client/pages/Embark/languagePickerData.ts
src/client/pages/Forever/components/LanguagePicker.tsx

Centralize language options by market.
Dynamically render language options on "Forever" page.
This change was missed likely because we have two isolated language pickers. So I thought it made sense to centralize the language options so when we add the next language we only need to do it in one place.
Perhaps these changes should be moved to the `locales.ts` module @styrelius is working on.

Add support for danish in Forever language picker

---

src/client/data/graphql.tsx
src/client/graphql/CreateQuoteBundle.graphql
src/client/pages/OfferDebugger/Debugger.tsx
src/client/pages/OfferDebugger/components/QuoteData.tsx
src/client/pages/OfferDebugger/components/QuoteFormDenmark.tsx
src/client/pages/OfferDebugger/components/QuoteFormNorway.tsx
src/client/pages/OfferDebugger/components/QuoteFormSweden.tsx

> FYI: there's some issue creating a house quote still. However, I think we can merge this and adress that separately.
The more generic version of the create bundle API has been released. This update addresses that.
This is the information we send now:
```json
{
"quoteCartId": "7fe19900-8dd2-4aae-bc4b-d79119674850",
"quotes": [
{
"firstName": "Sven",
"lastName": "Svensson",
"birthDate": "1995-09-29",
"ssn": "199509291234",
"email": "sven.svensson.trdlj@hedvig.com",
"data": {
"street": "Storgatan 1",
"zipCode": "12345",
"livingSpace": 23,
"householdSize": 1,
"subType": "RENT",
"type": "apartment"
}
}
]
}
```
I also:
- made sure that we send a unique email (to avoid conflicts)
- differentiated the buttons in the debugger a bit better
Keep up-to-date with the new QuoteCart API.
**Ticket(s): …

GRW-598 / Fix / Update Giraffe API in Offer Debugger

---

src/client/data/graphql.tsx
src/client/graphql/CreateOnboardingQuoteCart.graphql
src/client/pages/OfferDebugger/Debugger.tsx

Update `onboardingQuoteCart_create` mutation with new response type object.
GraphQL schema has been updated. 

Fix / Update response type of quote cart mutation

---

src/client/pages/OfferNew/index.tsx

Fix the redirect from `/offer` to landing page which happens if you try to go to `/offer` without a valid session.
The reason this was broken is that a switch had been made from the old `useCurrentLocale` hook to the new one in `/OfferNew/index.tsx`, but the `Redirect` path wasn't changed, which means it tries to use an object as the locale part of the path.
**Broken redirect:**
https://user-images.githubusercontent.com/42962286/144586748-460f98c1-0e40-4f8a-a1a0-3221f684a5f7.mov
**Fixed redirect:**
https://user-images.githubusercontent.com/42962286/144586766-cbed76ec-5e7f-444b-8a0a-cc094def9bd4.mov

Fix / Broken redirect from /offer to landing page

---

src/client/components/ModalNew.tsx
src/client/pages/Embark/index.tsx
src/client/pages/OfferNew/Checkout/index.tsx
src/client/utils/hooks/useLockBodyScroll.ts

Attempt to fix bug with `/offer` page being initially un-scrollable when it's first loaded after going through the onboarding flow.
**Bonus:** Minor refactoring to follow the general code style/patterns in the codebase.
After introducing the use of a `Modal` in `EmbarkRoot` the `useLockBodyScroll` cleanup function will apply style `overflow: hidden;` to the body on `/offer` page. This is caused by the `EmbarkRoot` component (for some reason) setting this style on the body. Since we don't know what problem was solved when this styling was introduced (two years ago) we'll try to just remove it and do some thorough checking of a review app in different viewports/browsers/devices.
Another solution would be to change the logic of the `useScrollLock` `useLayoutEffect` cleanup function - instead …

Fix / Offer page can't be scrolled

---

src/client/components/Badge/Badge.tsx
src/client/components/CampaignBadge/CampaignBadge.tsx
src/client/data/graphql.tsx
src/client/graphql/AppliedCampaign.graphql
src/client/pages/Offer/Checkout/index.tsx
src/client/pages/Offer/Introduction/Sidebar/index.tsx

We're in the process of integrate _QuoteCart API_ into _Offer_ page. Part of the strategy of this major refactor consists on doing the changes in an isolated mode. For example: If we need to do some changes on _OfferNew/Checkout/index.tsx_ we duplicate that file into _Offer/Checkout/index.tsx_ and make the changes there. That also means that any changes occurred in parallel on old offer files (_OfferNew/*_) needs to be propagated on the new files (_Offer/*_) as well. With that said, this PR is about to propagate recent changed occurred on _Checkout_ (#705 - add DiscountTag in Checkout view) into new _Checkout_ files. 
We need to keep propagating these changes so we don't loose any added feature/fix during _QuoteCart API_ integration.
**Ticket(s): …

refactor(GRW-689): propagate OfferNew/Checkout changes to Offer/Checkout

---

src/server/middleware/helmet.ts

Add OneTrust domain to CSP to be able to load the cookie banner
To be able to test the Cookie banner

Add OneTrust domain to CSP to be able to load the cookie banner

---

src/server/page.ts

Make sure we set correct html lang
To identify the language of the site to give correct info to screen readers, search engines and such. The cookie banner also follows the set html lang, that's how I discovered it :) 
https://user-images.githubusercontent.com/6661511/147944389-b953c19d-7247-4ea8-ad9f-e0e26c12b0d2.mov

Make sure we set correct html lang

---

src/client/pages/Offer/Introduction/Sidebar/CancellationOptions.tsx

`QuoteCancellationOption` is being displayed unconditionally due a change inserted by mistake in the codebase during the development of #735 . So this reverts to the original code.

fix(CancellationOptions): revert code inserted by mistake

---

src/client/pages/Offer/index.tsx
src/client/pages/OfferNew/index.tsx

- Changed `Checkout` toggle function so url gets updated properly; `redirect` is being used instead of `push` because IMHO as a user, I don't expect a UI like a _Sidebar_ incrementing browser's history list.
- Given a link that triggers Checkout opening (/sign), when user clicks on 'close' button
app goes back in the browser history which results on an empty browser tab; By clicking on `Checkout` close button, user should be able to see/interact with _Offer_ page.
https://user-images.githubusercontent.com/19200662/148051562-452831a5-db9e-4114-99c1-6d8cfc9bdb74.mov
https://user-images.githubusercontent.com/19200662/148051576-b181a588-09f5-415c-a9e3-d34d74e72101.mov

fix(Checkout): updated toggle method

---

src/client/pages/Forever/components/Intro/IntroStories.stories.tsx
src/client/pages/Forever/components/Intro/IntroStories.tsx
src/client/pages/Forever/components/Intro/PreOnoardingScreen.stories.tsx
src/client/pages/Forever/components/Intro/components.tsx
src/client/pages/Forever/components/RedeemCode.stories.tsx

Bugfix
Needs to be tested out in storybook.
Changed colors for text after the Forever page. 
The contrast was too low so you could not see the text 
https://hedvig.atlassian.net/browse/GRW-706
Before:
https://user-images.githubusercontent.com/63097139/148530287-1faa608e-e434-4f2b-a8e4-3d16fb74f85f.mp4
After: 
https://user-images.githubusercontent.com/63097139/148530242-27e56af6-74ae-4b00-ad0f-4ce66e63d874.mp4

Forever page  contrast fix

---

src/client/data/graphql.tsx
src/client/graphql/CheckoutStatus.graphql
src/client/graphql/CreateQuoteBundle.graphql
src/client/graphql/EditBundleQuote.graphql
src/client/graphql/fragments/QuoteDataFragment.graphql
src/client/pages/Offer/Checkout/index.tsx
src/client/pages/Offer/Introduction/Sidebar/CancellationOptions.tsx
src/client/pages/Offer/Introduction/Sidebar/StartDate.tsx
src/client/utils/sentry-client.ts

* Uses the edit quote query from the new QuoteCart api when updating data in the checkout form
* Replaces the setStartDate query with editQuote query as it was the same query
Makes for simpler code and logic.
This does not apply the same change to the User Details Form. This is because the createBundle query is atomic and therefore more suitable in the case where an update my fail on one quote but succeed in another.
**Ticket(s): [GRW-699]**
[GRW-699]: https://hedvig.atlassian.net/browse/GRW-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use editQuote query in checkout

---

src/server/page.ts
src/server/tracking.ts

- Add separate GTM scripts for staging/dev and prod. 
- Added a tracking file for GTM and Segment tracking scripts
This enables us to deploy and test tracking in staging a lot easier. We can deploy container versions to test in staging/dev before publishing to prod.
More info here: https://support.google.com/tagmanager/answer/6311518?hl=en

GRW-724 Add prod and dev scripts for GTM

---

src/client/pages/Offer/Checkout/UserDetailsForm.tsx
src/client/pages/Offer/Checkout/index.tsx
src/client/pages/Offer/Checkout/inputFields.tsx

* Add helper text to phone number field
* Add proper error message when format is invalid
* Make sure phone number field supports spaces
**Ticket(s): [GRW-765]**
[GRW-765]: https://hedvig.atlassian.net/browse/GRW-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRW-765 Add helpertext and space support for phone number on new offer page

---

src/client/components/inputs/index.tsx

It wasn't be possible to edit _Debugger_ forms (`debugger`/`offer-debugger`)
Inputs weren't getting `name` or `id` prop which is used by `formik.handleChange` callback to actual change their values.
**Ticket(s): [GRW-770](https://hedvig.atlassian.net/browse/GRW-770)**
[debugger](https://web-onboardi-fix-grw-77-2ftwiw.herokuapp.com/se-en/new-member/debugger)
[offer-debugger](https://web-onboardi-fix-grw-77-2ftwiw.herokuapp.com/se-en/new-member/offer-debugger)

fix(GRW-770): Fix Debugger forms editing

---

src/server/middleware/helmet.ts

Allow some additional scripts from OneTrust.
To make sure OneTrust geolocation functionality is enabled and that OneTrust can get consent data (that's the `clarity` scripts and tracking pixel.

Allow OneTrust geolocation script and tracking script

---

src/client/components/checkout/Footer.tsx
src/client/components/checkout/PaymentInfo.tsx

Refactoring of `Footer` and `PaymentInfo` components so that the footer button will always be rendered in the same place, regardless of whether the `PaymentInfo` component returns content, or if it returns `null`, in case of error.
There shouldn't be any visual changes.
Since in case of error in `PaymentInfo` there will also be errors somewhere else it feels like overkill to return some sort of error component here. Instead I just don't want to render anything. But since we might want to use the error modal with a semi-transparent backdrop in case of error (the same way it looks in case of signing error, although with different error modal content) I don't want to mess up the layout of the footer.

Fix / Checkout pages Footer styling

---

src/client/components/inputs/index.tsx

This was the issue:
Solution:
- Remove z-index setting for inputs
- Disable pointer events for chevron icon.
`z-index` was used to make the icon clickable: https://github.com/HedvigInsurance/web-onboarding/pull/253
However, I think it's a better idea to disable pointer events since `z-index` always causes these unintended layout issues.
**Ticket(s): [GRW-773]**
[GRW-773]: https://hedvig.atlassian.net/browse/GRW-773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix overflowing input text in Checkout

---

src/client/pages/Offer/Introduction/Sidebar/CancellationOptions.tsx
src/client/pages/OfferNew/Introduction/Sidebar/CancellationOptions.tsx

Consolidates the styles used by the two versions of `CancellationOptions` and fixes a bug related with spinner used by this component (check image in the following section)
As a fix, I'm overriding `flex` CSS property while using `Spinner` inside `CancellationOptions` (link here). But maybe a more robust solution would be refactor `Spinner` by removing it's [`flex` property](https://github.com/HedvigInsurance/web-onboarding/blob/master/src/client/components/utils.ts#L12) since it might be complicating things. But `Spinner` is being used on several files which would require more effort to check that nothing was broken:
So, for now I've decided leave as it is. Let me know your opinions about it.
CPS CancellationOptions redesign - #743 
**Ticket(s)**
_NA_
Access the review app linked below …

fix(CancellationOptions): align styles between versions

---

src/client/pages/Offer/Introduction/DetailsModal/Details/components/DetailInput.tsx
src/client/pages/OfferDebugger/components/QuoteData.tsx

Adding extra buildings through the edit details form was not working. This fixes the issue.
Also, added support for House + Accident in the debugger for SE
Known Issues:
The display name of extra buildings seems to be missing. This is an API issue that has been reported
**Ticket(s): [GRW-794](https://hedvig.atlassian.net/browse/GRW-794)**
https://user-images.githubusercontent.com/89857278/153561711-8cb18d80-bcdb-46c8-8b12-df603564e0d6.mov
[GRW-793]: https://hedvig.atlassian.net/browse/GRW-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRW-794-fix-adding-extra-building-in-details-modal

---

src/client/components/CampaignBadge/CampaignBadge.tsx
src/client/pages/OfferDebugger/components/QuoteData.tsx

- Fixes a bug on `CampaignBadge` component, responsible to skip the displaying of NO bundle discount (25%);
- Added support for the creation of _NO Home + Travel_ quotes to _Offer Debugger_
The issue was happening because `CampaignBadge` was relying on the presence of an active campaign in order to build and display discount badges. However, that specific discount is not being added by the API (it feels like it should tho. Not sure 🤔)
1. Access provided review app;
2. Create a _Norwegian Home + Travel_ quote and then go to the offer page
3. Check if _25% Discount_ is visible both on the _InfoSidebar_ and _Checkout_ components
**Ticket(s)**
[GRW-788](https://hedvig.atlassian.net/browse/GRW-788)

fix(GRW-788): displays NO bundle discount

---

src/client/pages/Offer/index.tsx

Make sure we don't include any auth token when loading quote cart offer page.
This gets picked up by the API and causes strange things to happen like the campaign code not being applied when calculating the price.
This is because the auth token is linked to a member entity. However, on the quote cart offer page, we can be sure that there's no relevant member to keep track of. If there's an auth token present -- it's an artifact.
When we move over to quote cart for all markets, this will no longer be needed.

Remove auth token when loading offer page (Quote Cart)

---

src/client/api/createQuoteBundleMutationSelectors.ts
src/client/pages/Offer/Checkout/index.tsx

Make sure to use `quoteIds` generated from the _editing information process_
When editing quote info we are actually creating new quotes instead of editing the existing ones. With that in mind, the problem was that in the scenario where users change some information like theirs names and then try to Complete the Purchase, we need to generate new quotes (editing) and then start the checkout process. The issue was that we weren't using the `quoteIds` generated by the editing process but the old ones, which makes users having to click [Complete Purchase] button twice so they can finish the purchase.
**Ticket(s): [GRW-844](https://hedvig.atlassian.net/browse/GRW-844)**
1. Use the Review app](https://web-onboardi-fix-grw-84-2cqwki.herokuapp.com/no-en/new-member/offer-debugger)mentioned below …

fix(Checkout): use proper quote ids while completing the purchase

---

src/client/data/graphql.tsx
src/client/pages/OfferNew/utils.ts
src/client/utils/tracking/adtraction.ts

Update `OfferNew/utils` and `tracking/adtraction` files due recent changes on API types;
Remove the obligation of fixing it in another PR which needs to update `graphql` auto generated file with `yarn codegen`
[apollo cache override](https://github.com/HedvigInsurance/web-onboarding/pull/855) - this one solves the others built issues (type validation)

chore: update due graphl api type changes

---

src/client/components/CampaignBadge/CampaignBadge.tsx
src/client/components/DiscountTag/DiscountTag.tsx
src/client/pages/Landing/landingPageData.ts
src/client/pages/Offer/Checkout/index.tsx
src/client/pages/Offer/Introduction/Sidebar/index.tsx
src/client/pages/OfferNew/utils.ts

Removes "25% DISCOUNT" badge from NO Combo (Home & Travel)
That discount is not applicable anymore
[GRW-896](https://hedvig.atlassian.net/browse/GRW-896)

fix(GRW-896): remove no combo discount badge

---

src/client/pages/Offer/Checkout/InsuranceSummaryDetails.tsx
src/client/pages/Offer/utils.ts
src/client/pages/OfferNew/types.ts

Update `GenericQuoteData`: floor is always a number.
Refactor `getAddress` to not include floor if "0".
The floor was displayed for all addresses (even house) but shouldn't.
**Ticket(s): [GRW-924]**
[GRW-924]: https://hedvig.atlassian.net/browse/GRW-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix address display without floor

---

e2e/cypress/integration/se-needer-house-flow.spec.ts

Update _Se Needer House Flow_ e2e test so the assertion looks for the right label
Is expected the button having the label "2" instead of "Two bathrooms"

test(se-needer-house): update button label

---

package.json
yarn.lock

`embark@2.6.1` add some changes that _enables chained redirect passages_
`embark@2.6.1` add some changes that _enables chained redirect passages_ which provides more flexibility for us to build embark flows
**Ticket(s): [GRW-915](https://hedvig.atlassian.net/browse/GRW-915)**

feat(GRW-915): bump embark 2.6.0 -> 2.6.1

---

src/client/components/ModalNew.tsx
src/client/pages/Offer/Introduction/DetailsModal/index.tsx

Fix a bug where Details Modal wasn't triggering a API request when "Save" button is clicked;
**Ticket(s): [GRW-952](https://hedvig.atlassian.net/browse/GRW-952)**
https://user-images.githubusercontent.com/19200662/160577492-85ea90d2-ee20-47c8-a756-ab5322341270.mov

bug(GRW-952): details modal save

---

package.json
yarn.lock

Bumps `embark@2.6.1` --> `embark@2.7.0`
So it get's access to _Single Option Select Action_

feat(GRW-936): bump embark@2.7.0

---

src/client/pages/OfferNew/Introduction/Sidebar/StickyBottomSidebar.tsx

Update old sticky button in offer page
Same button as sidebar. CPAS updates.
Before
After

 update footer button

---

package.json
src/client/components/DetailsModal/index.tsx
src/client/components/Headline/Headline.tsx
src/client/components/Modal.tsx
src/client/pages/ConnectPayment/components/TrustlyModal.tsx
src/client/pages/ConnectPayment/components/TrustlySpinnerPage.tsx
src/client/pages/ConnectPayment/sections/ConnectPayment.tsx
src/client/pages/Landing/Landing.tsx
src/client/pages/Landing/components/Card.tsx
src/client/pages/Offer/Checkout/InsuranceSummary.tsx
src/client/pages/OfferNew/Checkout/InsuranceSummary.tsx
src/client/pages/OfferNew/Introduction/DetailsModal/index.tsx
src/client/pages/OfferNew/Perils/PerilModal.tsx
src/client/pages/OfferNew/components.tsx
src/client/utils/globalStyles.tsx
yarn.lock

- Switch to new Hedvig fonts. Instead of FAVORIT we're using HEDVIG_LETTERS_STANDARD
- Bump Embark where I already updated the fonts
- Remove some deprecated colors, not even sure if those components are being used anymore?
- Adjust `line-heights` and `letter-spacing` with a new spec Zak and I worked on. We're now using unit less values for line-heights for ease of use.
We're launching the new typeface across all channels on Monday 25/4
https://user-images.githubusercontent.com/6661511/164434878-843149c4-1235-49db-896d-3a56632b55a3.mov
https://user-images.githubusercontent.com/6661511/164434889-0071c203-c2de-4877-9ee6-ebc834426566.mov

Switch to new Hedvig fonts

---

src/client/api/createQuoteBundleMutationSelectors.ts
src/client/api/quoteBundleSelectors.ts
src/client/api/quoteCartQuerySelectors.ts
src/client/pages/Offer/Checkout/InsuranceSummaryDetails.tsx
src/client/pages/Offer/Introduction/HeroOfferDetails.tsx
src/client/pages/Offer/index.tsx
src/client/pages/OfferNew/Introduction/HeroOfferDetails.tsx
src/client/pages/OfferNew/types.ts
src/client/pages/OfferNew/utils.ts
src/client/utils/hooks/useSelectedInsuranceTypes.ts
src/client/utils/tracking/gtm.ts

Adapt offer page to be able to show insurances that are not house/apartment
This PR mainly makes sure that the page doesn't crash when a non-house/apartment quote is provided, so that we can fan out the remaining tasks.
* Use contract type to determine which quote bundle that is selected, and what is shown in the URL. This is because all car quote variations have the same quote type, but not same contract type. This also happens to work for other bundles.
* Adapt SummaryDetails to only show information that's available with the current data.
Do we need some regression testing on this before I ship it to production? I have tested to render the offer page with all variations that exist in Sweden and it looks good.
Since we need to sell car insurance in web-onboarding we need to be able to …

GRW-1001 / Feature / Adapt offer page to show car insurance

---

src/client/pages/Offer/Checkout/UserDetailsForm.tsx

We changed the way the debouncing works in the SSN field on checkout form. This creates an infinite submit loop.
This reverts the change

Revert change to debounce function for SSN

---

src/client/components/Table/Table.stories.tsx
src/client/components/Table/Table.test.tsx
src/client/components/Table/Table.tsx
src/client/components/Table/__snapshots__/Table.test.tsx.snap
src/client/components/icons/IconsOverview/IconsOverview.tsx
src/client/components/icons/ThinTick.tsx
src/client/components/utils/margins.ts

This PR:
- Adds `ThinTick` icon which is in Figma files but missing from the repository (will happily take suggestions on naming...)
- Adds margins util so that we can add `mt`, `mx` etc margins for components instead of adding custom styling everywhere
- Adds Table component with API heavily inspired by [MUI](https://mui.com/material-ui/react-table/) and Kent C. Dodds [Compound Components](https://kentcdodds.com/blog/compound-components-with-react-hooks)
GRW-1062 ticket says that we should add a comparison table to the offer page. This is a component for that use-case. One of the stories mimics what we need to show visually.
**Ticket(s): [GRW-1062]**
Our many ways to show checkmarks:
Basic data:
As a comparison table:
This is the [Figma …

GRW-1062 / feat / add table component

---

src/client/pages/Offer/Introduction/Sidebar/StartDate.tsx

Changes the parameters used to determine the necessity of 'locking start date' selection based on _current insurer_
The logic used previously in Offer Page for that goal can be described as follow:
> _An insurance that should be cancelled by Hedvig is the one which its quote has a **current insurer associated with it**. With that, there's no point of letting users picking a start date since it can be automatically defined: starts when your old insurance expires_
However that might not be so accurate since there's the possibility of having quotes which its current insurer aren't switchable, which means Hedvig can't cancel them automatically. Therefore, the logic has changed for something that can be described as following:
> _An insurance that should be cancelled by Hedvig is the one which …

fix(GRW-1048): NO Accident - Current insurer skip button

---

src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
src/client/pages/Checkout/CheckoutPayment/index.tsx
src/client/pages/ConnectPayment/components/useAdyenCheckout.tsx
src/client/utils/hooks/useQuoteCartData.ts

- Added payment token inside of Adyen.
-  Changed the logic of IsPaymentConnected to get triggered when payment has been succesful instead of if payment token is added to the quoteCart
In order to get better tracking backend now return a paymentTokenID even if connect_payment fails. The id gets added to the quoteCart . This enables us to see what happened to the payment based on the quoteCart.

Grw-1078 / Cpas add paymentTokenId

---

src/client/api/quoteBundleSelectors.ts
src/client/api/quoteCartQuerySelectors.ts
src/client/api/quoteSelector.ts
src/client/pages/Offer/index.tsx
src/client/utils/tracking/gtm/dataLayer.ts
src/client/utils/tracking/gtm/trackOfferEvent.ts
src/client/utils/tracking/gtm/trackOfferGTM.ts
src/client/utils/tracking/hooks/useTrackOfferEvent.ts

Adds the following and removes the following fields in the GTM event tracking
(-) insurance_type: Does not scale, can be deduced from the has_home, has_house, has_accident, has_travel, ownership_type
(+) has_house: To track if bundle has house insurance
(+) ownership_type: RENT | OWN
(-) initial offer & current_offer: Do not scale and will be deduced from the quoteCart id
(-) switch_to: not needed
(+) switch_from: does not scale, was changed to a list of booleans instead of specific strings for each type
(-) current_insurer: does not make sense we can have more than one (eg. NO house + travel) and does not scale
This has been sinced with @sonnyandersson1 
Single strings for each bundle combination does not scale.

GRW-1021 Add support for house NO in GTM tracking and small refactoring

---

src/client/components/DetailsModal/Details/NorwegianHouseDetails.tsx
src/client/components/DetailsModal/Details/SwedishHouseDetails.tsx
src/client/components/DetailsModal/Details/components/DetailInput.tsx

Filter out ExtraBuildings options list on Norway so it matches the one we show during the Embark flow
Not all options are available in Norway so there is no point on displaying all of them
**Ticket(s): [GRW-1116](https://hedvig.atlassian.net/browse/GRW-1116)**

fix(GRW-1116): update available options

---

src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
src/client/pages/ConnectPayment/components/useAdyenCheckout.tsx
src/client/utils/tracking/gtm/types.ts

New tracking event for payment connection failure instead of signing. Minor adjustment for padding so we don't hide content on smaller screens. 
Changed payment flow so a new event is required.

 added new tracking event

---

src/client/data/graphql.tsx
src/client/graphql/ContractFaq.graphql
src/client/graphql/ContractFaqs.graphql
src/client/pages/Offer/index.tsx
src/client/pages/OfferNew/FaqSection.tsx
src/client/pages/OfferNew/Tabs/Tabs.tsx
src/client/pages/OfferNew/index.tsx

In order to launch Car we want to have Car-specific FAQ content on the Offer page. This means that we must get FAQ content based on what type of insurance(s) we're showing on the Offer page, not just a generic one like today. This should also work for all other data types on the offer page, not just Car.
These are the conditions:
- We have a number of bundles on the offer page, some will have different _insurance type_ (SE_CAR, SE_HOME etc), and some will have different _contract type_ (SE_CAR_HALF, SE_CAR_FULL etc)
- FAQs in PCMS are organized by _contract type_
- It's will be the same FAQ content for all of Car's contract types
- We only want one FAQ for Car on the offer page
We request FAQ:s for all insurance types from Giraffe/PCMS. Giraffe will take care of filtering duplicates …

GRW-1029 / feat / Load FAQ from PCMS

---

package.json
src/client/components/Accordion/Accordion.stories.tsx
src/client/components/Accordion/Accordion.tsx
src/client/pages/OfferNew/ComparisonTable/ComparisonTable.tsx
src/client/pages/OfferNew/FaqSection.tsx
src/types/react-animate-height.d.ts
yarn.lock

This PR:
- Tweaks the common Accordion component so that it can be re-used in both FAQ section and Comparison modal
- Adds `AccordionContext` so keep track of which items that are expanded
- Adds a default icon that can be reused (also possible to use your own if you want to, see stories)
- Updates FAQ section to use the updated Accordion
- Updates Comparison modal to use the updated Accordion
- Updates `react-animate-height` to latest version that supports ARIA attributes and `id`
Example usage with "single" mode, where only one item is expanded at the time:
```tsx
<Accordion mode="single">
<AccordionItem>
<AccordionTrigger>
Icon?
<AccordionTriggerIcon />
</AccordionTrigger>
<AccordionContent>
This example uses the default icon
</AccordionContent>
</AccordionItem>
<AccordionItem> …
```

Feat / Create common Accordion component

---

src/client/api/quoteBundleSelectors.ts
src/client/components/DetailsModal/index.tsx

* First issue is that we choose house insurance MainQuote when it is there, but house insurance does not include the "isStudent" data. That is why the form shows isStudent as "no" even if it is a yes. The solution here is to look through the whole bundle for an insurance that has isStudent.
* Second issue is that we discard form values that are boolean and set to false, so there was no way to set isStudent from true to false
Users should be able to edit the student status in the edit details modal
**Ticket(s): [GRW-1178] [GRW-1172] [GRW-1173]**
[GRW-1178]: https://hedvig.atlassian.net/browse/GRW-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRW-1172]: https://hedvig.atlassian.net/browse/GRW-1172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

GRW-1178-1172-1173 Fix issues with isStudent in edit modal

---

src/client/components/DetailsModal/index.tsx

Fix edit details form when editing household size / number co-insured.
Before we defaulted to the current value when `householdSize - 1` was falsy. Since 0 is falsy in JS it meant that you couldn't change to `householdSize = 1` 🙃 
You can't set household size to 1 in the edit details form.

Fix / Avoid defaulting to existing co-insured for falsy values

---

src/routes.tsx

As we've launched House NO as an iteration of Accident NO we've created two onboarding flows:
- `onboarding-NO`: which handles Home Contents, Accident, and Travel promises
- `onboarding-NOv2`: which handles Home Contents, House, Accident, and Travel promises
However, the ultimate goal was to have a single onboarding flow in NO to improve maintainability. With that said, this series of PRs aims to unify the onboarding flow in NO.
Update `routes` so the correct flow gets loaded when `[no-en|no]/new-member` is accessed
`onboarding-NOv2` ---> `onboarding-NO`
[embark](https://github.com/HedvigInsurance/embark/pull/981)
[racoon](https://github.com/HedvigInsurance/racoon/pull/228)
**Ticket(s): [GRW-1133](https://hedvig.atlassian.net/browse/GRW-1133)**

refact(GRW-1133): unify onboarding flow: onboarding-NO

---

src/routes.tsx

enables onboarding-DK flow unconditionally
A main component of House DK is a single onboarding flow so as part of the release of it we should make that flow available unconditionally
**Ticket(s): [GRW-876](https://hedvig.atlassian.net/browse/GRW-876)**

feat(onboarding-dk): enables onboarding flow unconditionally

---

src/client/pages/Landing/Landing.tsx
src/client/pages/Landing/landingPageData.ts
src/routes.tsx
src/server/meta.ts
src/server/page.ts

Move rendering of `<link>` meta tags to the server instead of rendering them client side.
Even though Google can in some sense crawl SPA pages it's better to render SEO-related elements on the server.
This PR makes the rendered document go from:
```html
<!doctype html>
<html lang=en>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=1.2, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Get a price quote | Hedvig</title>
</head>
<body>
<script nonce="80634d2a-17fe-4316-8b23-6af5649833be" src="/new-member-assets/app-8aae02aec04f1395806c.js"></script><script nonce="80634d2a-17fe-4316-8b23-6af5649833be" src="/new-member-assets/common-993d5a13ecd62a9a9b80.js"></script>
</body> …
```

Fix/ Render SEO links on server

---

src/client/pages/OfferNew/Perils/AmountCollection/index.tsx
src/client/pages/OfferNew/types.ts
src/client/pages/OfferNew/utils.ts
src/client/utils/testData/offerDataMock.ts

Use insurable limits from the server as they are, without mapping on type
We can sometimes get several insurable limits with the same `type` from BE since there's no restriction on unique-ness there: 
This caused some insurable limit items not to show in production because they were accidentally the same type. I think we should allow multiple items of the same type if the BE allows it.
The problem was that we mapped this array into a Map keyed on `type` which meant that we only showed one of the array items on the page:
After this PR we show all insurable limits as they are sent from BE:
I guess this was used to not get duplicates, but it seems it's not needed for bundles either, still works:
https://user-images.githubusercontent.com/1343979/173360122-b66fe86e-9606-4882-b8de-c34cf637e53a.m …

fix / Use insurable limits from the server as they are

---

src/client/pages/OfferNew/Perils/AmountCollection/AmountItem.tsx

Use flexbox to bottom-align content when the height (amount of content) differs between cards on the same row.
Before:
After (notice first card's content is aligned to bottom):

Use flexbox to align items to bottom when height differs

---

src/client/pages/Landing/Landing.tsx
src/client/utils/tracking/gtm/dataLayer.ts
src/client/utils/tracking/gtm/useTrackEvent.test.ts
src/client/utils/tracking/gtm/useTrackEvent.ts
src/server/page.ts
src/shared/clientConfig.ts

This PR ports `useTrackEvent` from https://github.com/HedvigInsurance/racoon/pull/233 and adds tracking to the "SE home" landing page according to GRW-1200.
A question is if it's worth trying to get `referer` from server to the client? 
Also, it seems the pages are rendered at least twice (at least in local testing) so I had to also keep track of whether the hook has called its function or not. Maybe not the prettiest solution?
Add event tracking to different landing pages between racoon and web-onboarding now that the flow has grown in complexity.
**Ticket(s): [GRW-1200]**
[GRW-1200]: https://hedvig.atlassian.net/browse/GRW-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRW-1200 / feat / Track onboarding events

---

src/client/components/Switch.tsx

Removes undesired line-height from icon since
**Before**
**After**
It adds some vertical spacing take makes difficult align things vertically.
It was added as a side effect of #1113

styles(Switch): removed undesired line-height from icon

---

src/client/pages/Offer/Checkout/Checkout.helpers.ts
src/client/pages/Offer/Checkout/index.tsx

Always fetch latest quote cart before trying to sign.
We still run into errors where the request to sign quotes fails since the quotes are no longer associated with the cart.
The reason for this is some mismatching react state.
Therefore it should be safest to always fetch the cart fresh before deciding which quote IDs to sign.

Prevent signing non-quote cart quotes

---

src/client/components/StandaloneProductCard.tsx
src/client/pages/Offer/ProductSelector/Selector.tsx

- `MainProductCard` --> `StandaloneProductCard`
It seems to be the correct name
I've realised now that it would be better have done that up in the stack. I'm sorry for the trouble 😬 
**Ticket(s): [GRW-1337](https://hedvig.atlassian.net/browse/GRW-1337)**

GRW-1337-refact: MainProductCard --> StandaloneProductCard

---

src/client/pages/Offer/index.tsx
src/client/utils/hooks/useSelectedInsuranceTypes.ts

Update URL accordingly in case offer page get's loaded without any `type` search parameter
To avoid inconsistent UI where offer gets loaded without any Product card selected
**Ticket(s): [GRW-1464](https://hedvig.atlassian.net/browse/GRW-1464)**
https://user-images.githubusercontent.com/19200662/188846848-8913b572-629a-4542-b99c-b11c02f10347.mov
Try to remove `type` parameter and then reload the page

GRW-1454 - fix(Offer): sync url on first load

---

src/client/pages/Offer/Introduction/Sidebar/StickyBottomSidebar.tsx

Change `SitckBottomSidebar` so it preserves query parameters while redirecting.
Query parameters should be preserve otherwise _Pentagon House Cross Sell_ UI will be inconsistent while redirecting to checking page using that button
**[Review App](https://web-onboardi-grw-1478-b-hjf82w.herokuapp.com/no-en/new-member/offer/3970252f-3557-4362-b16f-4a0fe607a15d?type=NORWEGIAN_HOME_CONTENT)**
_You need to use mobile screen dimensions to trigger the appearance of that button_
**Ticket(s): [GRW-1478](https://hedvig.atlassian.net/browse/GRW-1478)**

fix(SitckBottonSidebar): preserve query params while redirecting

---

src/client/components/ErrorModal.tsx
src/client/components/ModalNew.tsx
src/client/pages/Checkout/shared/ErrorModal.tsx
src/client/pages/Embark/ErrorModal.tsx

Just some small updates to modal handling in web-onboarding in regards to working with GRW-1421. 
1. Close modals with Escape button press
2. Move button definitions of Error Modal into the actual component
1. It's annoying not to be able to close Modals with Escape and it's a common user interaction pattern 
2. They're duplicated across the code base and I don't want to duplicate them into yet another component (GRW-1421's modal)
**Ticket(s): sort of [GRW-1421]**
[GRW-1421]: https://hedvig.atlassian.net/browse/GRW-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRW-1421 / feat / Close modal with escape

---

src/client/pages/Offer/ProductSelector/Selector.tsx
src/client/pages/Offer/ProductSelector/index.tsx

Displays _Product Selector_ based on the presence of main/additional quotes
Otherwise the UI could be inconsistent; E.g: Display "Additional Coverage" subtitle when there's no additional coverage quotes. 
**Ticket(s): [GRW-1484](https://hedvig.atlassian.net/browse/GRW-1484)**

GRW-1483 - fix(ProductSelector): conditionally displayed based on standalone/addtional coverage presence

---

src/client/pages/Checkout/CheckoutDetails/CheckoutDetails.tsx
src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
src/client/pages/Checkout/CheckoutPayment/index.tsx
src/client/pages/Checkout/shared/ErrorModal.tsx

Show specific error for manual review error in new checkout
Add `isManualReviewRequired`-prop to `CheckoutErrorModal`.
Refactor `CheckoutPayment` component to derive error state based on checkout error.
We should show a specific error and email address for people that require manual review / fail on debt check.
This already works in the Swedish checkout but was not implemented in the new checkout.
**Ticket(s): [GRW-1496]**
[GRW-1496]: https://hedvig.atlassian.net/browse/GRW-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show specific error for manual review error in new checkout

---

src/client/components/buttons.tsx
src/client/pages/Checkout/CheckoutDetails/CheckoutDetails.tsx
src/client/pages/Checkout/CheckoutPayment/CheckoutPayment.tsx
src/client/pages/Offer/Introduction/Sidebar/Sidebar.tsx
src/client/pages/Offer/Introduction/Sidebar/StickyBottomSidebar.tsx
src/client/pages/Offer/ProductSelector/Selector.tsx
src/client/utils/hooks/useSelectedInsuranceTypes.ts
src/client/utils/tracking/hooks/useSendDatadogAction.ts
src/client/utils/tracking/hooks/useTrackOfferEvent.ts
src/client/utils/tracking/hooks/useTrackSignedCustomerEvent.ts

Use SessionStorage instead of URL to store selected insurance types.
Use URL to store initial insurance types (from Embark).
Update previous users of `getSelectedInsuranceTypes`.
Remove handling of search params in new Checkout.
We have a bug in production where we lose this information.
Reference: https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1663578089945019
This results in users signing other insurances than they intended.

Fix issue forgetting selected insurance after Adyen

---

.env.example
package.json
src/client/pages/Embark/index.tsx
src/server/config.ts
src/server/page.ts
src/shared/clientConfig.ts
yarn.lock

Add possibility to pass config variables from web-onboarding to Embark upon init
We need to configure which URL Insurely loads from depending on environment and there is no such concept in Embark really. There is obviously no way for the components that are published as an NPM package to be different per environment so instead they need to receive a config from outside.
I tried coming up with a way to do this server-side, either in Embark or Giraffe but in the end it seemed to be simpler just to use the env variables from web-onboarding.
See also https://github.com/HedvigInsurance/embark/pull/1030
**Ticket(s): [GRW-1512]**
[GRW-1512]: https://hedvig.atlassian.net/browse/GRW-1512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRW-1512 / Add possibility to pass env variables from to Embark

---

src/client/data/graphql.tsx
src/client/graphql/EditBundleQuote.graphql

Also include `possibleVariations` info into edit bundle mutation so we get `QuoteBundleVariant.bundleCost` properly updated after a quote gets executed.
The issue was introduced [here](https://github.com/HedvigInsurance/web-onboarding/pull/735) as I thought we could just request information about `BunledQuote`s after executing an edit quote mutation in order to get the cache proper updated. However that was not enough since `bundleCost` is get from the `QuotebundleVariant.bundle`.
**Ticket(s): [GRW-1559](https://hedvig.atlassian.net/browse/GRW-1559)**
https://user-images.githubusercontent.com/19200662/192516972-550b69f7-45d6-4f69-ab03-f55744230923.mov

GRW-1559 - bug: proper update cache so price gets proper updated

---

.env.example
package.json
src/client/pages/Embark/index.tsx
src/server/config.ts
src/server/page.ts
src/shared/clientConfig.ts
yarn.lock

Because of https://github.com/HedvigInsurance/embark/pull/1044 the configuration signature for Insurely has changed. It's technically a breaking change but the flow and iframe isn't used by any end-users so it's not a problem.
We need to use different Insurely Client IDs depending on which Embark flow we initialize - Insurely wants us to use different Client IDs for different products.
**Ticket(s): [GRW-1579](https://hedvig.atlassian.net/browse/GRW-1579)**

Pass in Insurely client ids for both Home and Car

---

src/server/config.ts

Update default embark stories for NO and DK
With the release of _Pentagon House Cross Sell_ some of the embark stories for NO and DK became obsolete. The obsolete one are the ones used by default here, so that needs to change.
[embark changes](https://github.com/HedvigInsurance/embark/pull/1051)
**Ticket(s): [GRW-1594](https://hedvig.atlassian.net/browse/GRW-1594)**

GRW-1594 - chore: update default embark stories for NO and DK

---

src/client/components/DetailsModal/index.tsx

Fix issue with edit details modal that changes all `subType` fields for Car to the same value (selected insurance).
It breaks the onboarding flow.

Fix edit details for Car

---

src/client/pages/Offer/InsuranceSelector/InsuranceSelector.helpers.ts
src/client/pages/Offer/InsuranceSelector/index.tsx
src/client/pages/Offer/Introduction/Sidebar/StartDate.tsx
src/client/pages/Offer/index.tsx
src/client/utils/hooks/useExternalDataCollection.ts

Use renewal date for the old insurance from Insurely data collection to suggest start date on Offer page.
Add new reusable `useExternalDataCollection` hook. Refactor `InsuranceSelector` to use new hook.
Refactor `StartDate` component and add button to update start date to match renewal date of old insurance.
We want to help people switch and BankSignering requires us to send a date for the start of the new insurance.
This only works for Car now but when we can match exposure for other insurance types we can enable this same feature.
There's no way to set a default date in our date picker -- that's why I went with a button the user has to click. This is also to inform the user where the date comes from. I made the button disabled if the start date already matches the renewal date to …

Use renewal date from Insurely as suggested start date

---

package.json
yarn.lock

Update Embark to latest version.
Correctly configure language of Insure iFrame
N/A

Update Embark to version 2.22.1

---

src/client/components/DateInput/index.tsx
src/client/pages/Offer/Introduction/Sidebar/StartDate.tsx

Refactor how we populate start date from Insurely for Car on offer page.
Re-use the same solution inside `DateInput` but make it possible to set a defined start date or `null`.
It was confusing with 2 different solutions/labels.
This solution is not very scalable so if we do additional changes here we should consider a bigger refactoring.

Refactor how to populate start date from Insurely

---

src/client/pages/Embark/index.tsx

BUG: When going through the Car onboarding and using compare your price with Insurely you would get redirected back to the step before `/price-comparison` when having authenticated with BankID. This is due to Safari reading the redirect/reload as a history `POP` event and hence causing the user to end up on the previous passage in Embark.
We manipulate the history in the following way:
```js
historyGoBackListener={(goBack) =>
history.listen((_: any, action: string) => {
// This is to enable the browsers back button to navigate to the previous passage in embark
if (action === 'POP' && state.history.length > 1) {
goBack()
}
})
}
```
I tried to find a way to differentiate between hitting the navigate back button and the redirect from BankID, but couldn't find a straight forward solution. To …

GRW-1670 / Bug / Avoid iOS Safari going back to previous passage after BankID redirect

---

package.json
yarn.lock

Use sans-serif font in Insurely iframe
See PR https://github.com/HedvigInsurance/embark/pull/1071
[GRW-1680]
[GRW-1680]: https://hedvig.atlassian.net/browse/GRW-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump embark to 2.22.3

---

package.json
yarn.lock

Upgrade to latest Embark 2.23.0.
This enables automatic pre-selected company in Insurely iframe.
N/A.
**Ticket(s): [GRW-1682]**
[GRW-1682]: https://hedvig.atlassian.net/browse/GRW-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade Embark v2.23.0

---

src/routes.tsx

Enable A/B testing with `SE-onboarding-car-v3` flow
1. Open the [Review app](https://web-onboardi-grw-1730-f-8nybv3.herokuapp.com/se-en/new-member/car) and observe the cookie with the format: `HEDVIG_EXP_[id]-id_g`
* If you got `0`, it means you've got selected to our current flow which asks you want to compare the price
*  If you got `1`, it means you've got selected to the new flow that displays the "compare" passage without asking for consent.
You can clear the cookie and star over in case you want to test both situations.
**Ticket(s): [GRW-1730](https://hedvig.atlassian.net/browse/GRW-1730)**

GRW-1730 - feat: enable SE car price matching flow A/B testing

---

src/client/pages/Checkout/CheckoutDetails/CheckoutDetails.tsx
src/client/utils/hooks/useQuoteCartData.ts

Make sure to update all quotes when changing information from _CheckoutDetails_ page
Otherwise that can be confusing for users that change some info while in the _CheckoutDetails_ page and then go back to _Offer_ page to realise their changes were not applied to all quotes.
E.g: Assume you're in the _Offer_ page and you can select between _Home_ and _Accident_. Your name is defined as "John Doe". You select only _Home_ and move forward to _CheckoutDetails_ page (click on [Continue to Checkout] button). You then update your name to "Arnold Doe". If you go back to _Offer_ page and check Details for accident only you'll se "John Doe" as your name, which is confusing.
**Ticket(s): [GRW-1833](https://hedvig.atlassian.net/browse/GRW-1833)**

fix(CheckoutDetails): change all quotes while editing info

---

src/client/utils/hooks/useQuoteCartData.ts

Skip blank fields in checkout summary when no home (content) quote is part of the selected variant.
New since the travel/accident standalone feature.
**Ticket(s): [GRW-1841]**
[GRW-1841]: https://hedvig.atlassian.net/browse/GRW-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Skip blank fields from Checkout details

---

src/client/components/DetailsModal/Details/NorwegianDetails.tsx

In Norway, always allow editing street + zip code in edit details modal on offer page.
New need when allowing to sign travel/accident standalone.
**Ticket(s): [GRW-1843]**
[GRW-1843]: https://hedvig.atlassian.net/browse/GRW-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NO: Allow editing address for travel/accident

---

src/client/components/DetailsModal/Details/DanishDetails.tsx
src/client/components/DetailsModal/Details/DanishHomeDetails.tsx
src/client/components/DetailsModal/Details/DanishHouseDetails.tsx
src/client/components/DetailsModal/Details/NorwegianDetails.tsx
src/client/components/DetailsModal/Details/NorwegianHomeDetails.tsx
src/client/components/DetailsModal/Details/NorwegianHouseDetails.tsx
src/client/pages/Offer/Checkout/UserDetailsForm.tsx

Fix edit details form to allow nullable first and last name inputs.
Make first and last name inputs optional in edit details modal (confirmed with Zak).
Fix checkout form to allow nullable first and last name inputs.
We show some very strange error messages when first/last name is null (see jira ticket).
We don't need first/last name when calculating price so it should be optional in edit modal.
**Ticket(s): [GRW-1849]**
[GRW-1849]: https://hedvig.atlassian.net/browse/GRW-1849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix error messages when first/last name is null

---

src/client/components/DetailsModal/Details/DanishDetails.tsx
src/client/components/DetailsModal/Details/DanishHomeDetails.tsx
src/client/components/DetailsModal/Details/DanishHouseDetails.tsx
src/client/components/DetailsModal/Details/NorwegianDetails.tsx
src/client/components/DetailsModal/Details/NorwegianHomeDetails.tsx
src/client/components/DetailsModal/Details/NorwegianHouseDetails.tsx
src/client/components/DetailsModal/Details/SwedishApartmentDetails.tsx
src/client/components/DetailsModal/Details/SwedishHouseDetails.tsx
src/client/components/DetailsModal/index.tsx

Wait before closing edit modal so all mutations respond first.
Update error message when household size field value is invalid.
We were reading a value outside the function before. This encloses the variable in the function scope so we are actually reading the value from the previous mutation 🤦🏻 Now we return the response and read it in the same context so they are always in sync.
I changed the error message as well since before it said "wrong format".
Thanks to @fredriklagerblad for reporting the issue!

Wait for response before dismissing edit modal

---

src/client/components/DetailsModal/index.tsx

Close button should be a regular button and not "submit" which is the default.
Avoid closing the form "on enter".

Override 'type' for close button

---

src/client/App.tsx
src/client/utils/tracking/hooks/useTrackAbPurchaseFlowRedirect.ts
src/client/utils/tracking/hooks/useTrackNewSiteExperiment.ts
src/shared/newSiteAbTest.ts

Send Analytics event when we see user selected for old site during AB testing
Simple hardcoded config, no feature flags - sending event is always safe, worst case is that it's ignored
Need to track conversion for new vs old site in Google Optimize

GRW-1963 / Feature / Track experiment_impression events for new vs old site

---

.env.example
src/server/exchangeToken.ts

Configure public host name to be able to correctly redirect from the server.
We do redirect after performing access token exchange. It was redirecting to the wrong host name.

Configure public host to correctly redirect from server

---

src/routes.tsx

* Removes reference to `SE-onboarding-car-v3` flow
That flow was added as part of an A/B testing experiment. The experiment is now [done](https://hedviginsurance.slack.com/archives/C0381RB3Z5E/p1671445971349189?thread_ts=1669881882.698709&cid=C0381RB3Z5E) and it was decided to keep the other flow, making this one obsolete.
[embark](https://github.com/HedvigInsurance/embark/pull/1100)
**Ticket(s): [GRW-1979](https://hedvig.atlassian.net/browse/GRW-1979)**
[GRW-1979]: https://hedvig.atlassian.net/browse/GRW-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRW-1979]: https://hedvig.atlassian.net/browse/GRW-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRW-1979 - refact: removes reference to car flow added for A/B testing

---

src/client/pages/Payment/Breadcrumbs.tsx
src/client/pages/Payment/Payment.tsx

Customize the "3rd step" of the checkout flow based on the "redirect_url" query parameter.
For some carts we include the switching assistant while other people go directly to confirmation page.

Breadcrumbs: customize next step based on redirectURL

---

src/client/pages/Payment/Payment.tsx
src/client/pages/Payment/useCreateTrustlyURL.ts

Expose `onError` event handler from trustly mutation.
Redirect users that fail to complete the trustly mutation to "hedvig-com".
Skip the `SessionTokenGuard` on the payment page since it doesn't do what we want it to do.
We don't want users to get redirected to "/new-member" when they fail to complete the trustly mutation.

Redirect users that fail to connect payment back to store

---

src/server/exchangeToken.ts

Add early HTTP 204 to token exchange route to HEAD requests, we should not consume authorization_code in this case
Potentially fixes a problem a lot of members see

Don't do token exchange on HTTP HEAD requests
